#!/usr/bin/env python3
"""Translate lib/ocaml/keccak.ml (Keccak-f[1600] of the pure OCaml backend)
into Lean, for the proofs in formal/lean/Curve448Formal/KeccakOCaml.lean.

The OCaml file is generated by tools/gen_keccak_ocaml.py. This script does
not reuse that generator: it tokenizes and parses keccak.ml itself and
translates the parse tree, so the Lean definition is what the OCaml source
says, whatever produced it.

Accepted source. Everything outside `permute` and `round_constants` must be
token-for-token the `Lane` module below (the Lean side models `Lane.load`,
`Lane.store` and the externals by hand, so any change there must be looked
at). `round_constants` is an array of int64 literals. `permute` must be

    let permute (s : bytes) =
      let open Lane in
      for ROUND = LO to HI do
        let x = EXPR in ...
        store s OFFSET (EXPR); ...; store s OFFSET (EXPR)
      done

where EXPR is built from let-bound names, int64 literals, `load s OFFSET`,
`Array.unsafe_get round_constants ROUND` and the Lane operators `lxor`,
`land`, `lor`, `lsl`, `lsr`. OFFSET must be an int literal with
OFFSET mod 8 = 0 and OFFSET + 8 <= 200, and the right operand of `lsl`/`lsr`
an int literal in [0, 63]. Anything else is rejected.

Translation (with `let open Lane in`, the operators are Lane's externals):

    a lxor b   (%int64_xor)            a ^^^ b
    a land b   (%int64_and)            a &&& b
    a lor b    (%int64_or)             a ||| b
    a lsl n    (%int64_lsl, 0<=n<=63)  a <<< n     (n : Nat)
    a lsr n    (%int64_lsr, 0<=n<=63)  a >>> n     (logical shift)
    NL / 0xNL  (int64 literal)         N#64 / BitVec.ofInt 64 (-N)
    load s N                           load s N    (load, store: parameters)
    store s N e; rest                  let s := store s N (e); rest
    Array.unsafe_get round_constants r round_constants[r]!
    let x = e in rest                  let x := e; rest
    for r = lo to hi do body done      forTo lo hi (fun r s => body) s

OCaml gives lxor, land and lor one precedence level (left associative) and
lsl/lsr a higher one (right associative), unlike Lean; the output is
parenthesized from the parse tree, so no Lean precedence is relied upon
except left associativity of a chain of one operator.

Usage (from anywhere):
  python3 formal/tools/keccak_to_lean.py           # rewrite the Lean file
  python3 formal/tools/keccak_to_lean.py --stdout  # print it instead
  python3 formal/tools/keccak_to_lean.py --check   # exit 1 if it is stale

--check also compares the C source that formal/lean/Curve448Formal/Keccak.lean
models by hand (keccak_f1600 and its tables in lib/c/native/shake256.h) with
the verbatim copy quoted in that Lean file, and the three C tables with the
Lean definitions of KECCAK_ROUND_CONSTANTS, KECCAK_RHO and KECCAK_PI.
"""

import hashlib
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
OCAML_SRC = os.path.join(ROOT, "lib", "ocaml", "keccak.ml")
C_SRC = os.path.join(ROOT, "lib", "c", "native", "shake256.h")
LEAN_OUT = os.path.join(ROOT, "formal", "lean", "Curve448Formal", "KeccakOCamlGen.lean")
LEAN_C_MODEL = os.path.join(ROOT, "formal", "lean", "Curve448Formal", "Keccak.lean")

STATE_BYTES = 200

# The Lane module as modelled in KeccakOCaml.lean (compared token by token).
LANE_MODULE = """
module Lane = struct
  external ( lxor ) : int64 -> int64 -> int64 = "%int64_xor"
  external ( land ) : int64 -> int64 -> int64 = "%int64_and"
  external ( lor ) : int64 -> int64 -> int64 = "%int64_or"
  external ( lsl ) : int64 -> int -> int64 = "%int64_lsl"
  external ( lsr ) : int64 -> int -> int64 = "%int64_lsr"
  external get : bytes -> int -> int64 = "%caml_bytes_get64u"
  external set : bytes -> int -> int64 -> unit = "%caml_bytes_set64u"
  external swap : int64 -> int64 = "%bswap_int64"

  let[@inline] load s i = if Sys.big_endian then swap (get s i) else get s i

  let[@inline] store s i v =
    if Sys.big_endian then set s i (swap v) else set s i v
end
"""

BINOPS = {
    # OCaml operator: (Lean operator, OCaml precedence level, associativity)
    "lxor": ("^^^", 6, "left"),
    "land": ("&&&", 6, "left"),
    "lor": ("|||", 6, "left"),
    "lsl": ("<<<", 7, "right"),
    "lsr": (">>>", 7, "right"),
}
# Other OCaml infix operators at these levels, rejected if they occur.
OTHER_INFIX = {"asr", "mod", "*", "/", "**", "+", "-", "<", ">", "=", "<>", "&&", "||", "::", "@", "^"}


class Error(Exception):
    pass


# ---------------------------------------------------------------------------
# Lexer

TOKEN_RE = re.compile(
    r"""
    (?P<ws>\s+)
  | (?P<string>"(?:[^"\\]|\\.)*")
  | (?P<int>(?:0[xX][0-9a-fA-F][0-9a-fA-F_]*|[0-9][0-9_]*)[lLn]?)
  | (?P<ident>[A-Za-z_][A-Za-z0-9_']*(?:\.[A-Za-z_][A-Za-z0-9_']*)*)
  | (?P<attr>\[@[A-Za-z_.]+\])
  | (?P<sym>\[\||\|\]|->|:=|<-|[()\[\];:=,\-*+/<>|&^@.])
  """,
    re.VERBOSE,
)


class Tok:
    def __init__(self, kind, text, line):
        self.kind = kind
        self.text = text
        self.line = line

    def __repr__(self):
        return "%s:%r@%d" % (self.kind, self.text, self.line)


def tokenize(text):
    """Tokens of an OCaml source; comments (nested) become 'comment' tokens."""
    toks = []
    i, line = 0, 1
    while i < len(text):
        if text.startswith("(*", i):
            depth, j = 0, i
            while True:
                if j >= len(text):
                    raise Error("unterminated comment at line %d" % line)
                if text.startswith("(*", j):
                    depth += 1
                    j += 2
                elif text.startswith("*)", j):
                    depth -= 1
                    j += 2
                    if depth == 0:
                        break
                elif text[j] == '"':
                    m = re.compile(r'"(?:[^"\\]|\\.)*"').match(text, j)
                    if not m:
                        raise Error("unterminated string in comment at line %d" % line)
                    j = m.end()
                else:
                    j += 1
            body = text[i + 2:j - 2]
            toks.append(Tok("comment", " ".join(body.split()), line))
            line += text.count("\n", i, j)
            i = j
            continue
        m = TOKEN_RE.match(text, i)
        if not m:
            raise Error("cannot tokenize %r at line %d" % (text[i:i + 20], line))
        kind = m.lastgroup
        if kind != "ws":
            toks.append(Tok(kind, m.group(), line))
        line += m.group().count("\n")
        i = m.end()
    return toks


def code_tokens(toks):
    return [t for t in toks if t.kind != "comment"]


# ---------------------------------------------------------------------------
# Parser for the accepted subset


class Parser:
    def __init__(self, toks):
        self.toks = toks
        self.i = 0
        self.comments = []

    def skip_comments(self):
        while self.i < len(self.toks) and self.toks[self.i].kind == "comment":
            self.comments.append(self.toks[self.i].text)
            self.i += 1

    def peek(self, k=0):
        self.skip_comments()
        j = self.i
        seen = 0
        while j < len(self.toks):
            if self.toks[j].kind != "comment":
                if seen == k:
                    return self.toks[j]
                seen += 1
            j += 1
        return None

    def next(self):
        t = self.peek()
        if t is None:
            raise Error("unexpected end of file")
        self.skip_comments()
        self.i += 1
        return t

    def expect(self, text):
        t = self.next()
        if t.text != text:
            raise Error("line %d: expected %r, found %r" % (t.line, text, t.text))
        return t

    def at(self, text, k=0):
        t = self.peek(k)
        return t is not None and t.text == text

    def take_comments(self):
        c, self.comments = self.comments, []
        return c


def parse_int_literal(tok):
    """(value, is_int64) of an OCaml integer literal token (no sign)."""
    text = tok.text.replace("_", "")
    suffix = ""
    if text[-1] in "lLn":
        suffix, text = text[-1], text[:-1]
    if suffix == "n":
        raise Error("line %d: nativeint literal %s" % (tok.line, tok.text))
    value = int(text, 16) if text[:2] in ("0x", "0X") else int(text, 10)
    return value, suffix in ("l", "L"), text[:2] in ("0x", "0X")


# Expression AST: tuples
#   ("var", name) ("int", value) ("i64", value, spelling) ("load", offset)
#   ("rc", index_var) ("bin", op, lhs, rhs)


class ExprParser:
    def __init__(self, p, env, loop_var):
        self.p = p
        self.env = env  # name -> type ("int64" or "int" or "bytes")
        self.loop_var = loop_var

    def expr(self, level=6):
        """Parse an expression whose operators have precedence >= level."""
        lhs = self.prefix()
        while True:
            t = self.p.peek()
            if t is None:
                return lhs
            if t.text in BINOPS:
                op, prec, assoc = BINOPS[t.text]
                if prec < level:
                    return lhs
                self.p.next()
                rhs = self.expr(prec if assoc == "right" else prec + 1)
                lhs = ("bin", t.text, lhs, rhs, t.line)
            elif t.text in OTHER_INFIX:
                raise Error("line %d: operator %r is not supported" % (t.line, t.text))
            else:
                return lhs

    def prefix(self):
        t = self.p.peek()
        if t.text == "-":
            self.p.next()
            lit = self.p.next()
            if lit.kind != "int":
                raise Error("line %d: unary minus is only supported on literals" % t.line)
            value, is64, _ = parse_int_literal(lit)
            if not is64:
                raise Error("line %d: negative int literal" % t.line)
            if value > 2 ** 63:
                raise Error("line %d: int64 literal out of range" % t.line)
            return ("i64", -value, "-" + lit.text)
        return self.application()

    def application(self):
        t = self.p.peek()
        if t.kind == "ident" and t.text in ("load", "Array.unsafe_get", "store"):
            self.p.next()
            if t.text == "load":
                self.p.expect("s")
                return ("load", self.offset(), t.line)
            if t.text == "Array.unsafe_get":
                self.p.expect("round_constants")
                idx = self.p.next()
                if idx.text != self.loop_var:
                    raise Error("line %d: round_constants indexed by %r, not the loop variable"
                                % (idx.line, idx.text))
                return ("rc", idx.text, t.line)
            raise Error("line %d: store inside an expression" % t.line)
        return self.atom()

    def atom(self):
        t = self.p.next()
        if t.text == "(":
            e = self.expr()
            self.p.expect(")")
            return e
        if t.kind == "int":
            value, is64, is_hex = parse_int_literal(t)
            if is64:
                limit = 2 ** 64 if is_hex else 2 ** 63
                if value >= limit:
                    raise Error("line %d: int64 literal out of range" % t.line)
                return ("i64", value, t.text)
            return ("int", value, t.line)
        if t.kind == "ident":
            if t.text not in self.env:
                raise Error("line %d: unbound or unsupported name %r" % (t.line, t.text))
            return ("var", t.text, t.line)
        raise Error("line %d: unexpected %r" % (t.line, t.text))

    def offset(self):
        t = self.p.next()
        if t.kind != "int":
            raise Error("line %d: byte offset must be an int literal" % t.line)
        value, is64, _ = parse_int_literal(t)
        if is64:
            raise Error("line %d: byte offset must be an int" % t.line)
        if value % 8 != 0 or value + 8 > STATE_BYTES:
            raise Error("line %d: byte offset %d is not an in-bounds lane offset" % (t.line, value))
        return value


def typecheck(e, env):
    """Type of an expression; raise Error when the translation would not be exact."""
    kind = e[0]
    if kind == "var":
        return env[e[1]]
    if kind == "int":
        return "int"
    if kind in ("i64", "load", "rc"):
        return "int64"
    if kind == "bin":
        _, op, lhs, rhs, line = e
        if typecheck(lhs, env) != "int64":
            raise Error("line %d: left operand of %s is not int64" % (line, op))
        if op in ("lsl", "lsr"):
            if rhs[0] != "int" or not 0 <= rhs[1] <= 63:
                raise Error("line %d: shift amount of %s must be an int literal in [0, 63]"
                            % (line, op))
        elif typecheck(rhs, env) != "int64":
            raise Error("line %d: right operand of %s is not int64" % (line, op))
        return "int64"
    raise Error("unknown expression %r" % (e,))


# ---------------------------------------------------------------------------
# Printing Lean


def lean_i64(value, spelling):
    if value < 0:
        return "BitVec.ofInt 64 (%d)" % value
    text = spelling.replace("_", "")[:-1]  # drop the L suffix
    return "%s#64" % text


def lean_expr(e, top=True):
    kind = e[0]
    if kind == "var":
        return e[1]
    if kind == "int":
        return str(e[1])
    if kind == "i64":
        s = lean_i64(e[1], e[2])
        return s if top or value_is_atomic(s) else "(%s)" % s
    if kind == "load":
        s = "load s %d" % e[1]
        return s if top else "(%s)" % s
    if kind == "rc":
        s = "round_constants[%s]!" % e[1]
        return s if top else "(%s)" % s
    if kind == "bin":
        _, op, lhs, rhs, _ = e
        lop = BINOPS[op][0]
        # A left operand with the same left-associative operator needs no
        # parentheses (Lean's ^^^, &&&, ||| are infixl); anything else does.
        if lhs[0] == "bin" and lhs[1] == op and BINOPS[op][2] == "left":
            ls = lean_expr(lhs, top=True)
        else:
            ls = lean_expr(lhs, top=False)
        rs = lean_expr(rhs, top=False)
        s = "%s %s %s" % (ls, lop, rs)
        return s if top else "(%s)" % s
    raise Error("unknown expression %r" % (e,))


def value_is_atomic(s):
    return re.fullmatch(r"[0-9A-Za-z_]+#64", s) is not None


# ---------------------------------------------------------------------------
# Translation of keccak.ml


def translate(src):
    toks = tokenize(src)
    lane_toks = [t.text for t in code_tokens(tokenize(LANE_MODULE))]
    p = Parser(toks)

    # module Lane = struct ... end
    got = []
    for _ in lane_toks:
        got.append(p.next().text)
    if got != lane_toks:
        raise Error("module Lane differs from the version modelled in KeccakOCaml.lean; "
                    "update the Lean model of Lane and LANE_MODULE in this script")
    p.take_comments()

    # let round_constants = [| ... |]
    p.expect("let")
    p.expect("round_constants")
    p.expect("=")
    p.expect("[|")
    constants = []
    while not p.at("|]"):
        t = p.next()
        if t.kind != "int":
            raise Error("line %d: round constant is not an int literal" % t.line)
        value, is64, is_hex = parse_int_literal(t)
        if not is64 or value >= (2 ** 64 if is_hex else 2 ** 63):
            raise Error("line %d: round constant is not an int64 literal" % t.line)
        constants.append((value, t.text))
        if not p.at("|]"):
            p.expect(";")
    p.expect("|]")
    p.take_comments()

    # let permute (s : bytes) = let open Lane in for r = lo to hi do ... done
    for text in ("let", "permute", "(", "s", ":", "bytes", ")", "=", "let", "open", "Lane", "in",
                 "for"):
        p.expect(text)
    loop_var = p.next()
    if loop_var.kind != "ident" or "." in loop_var.text:
        raise Error("line %d: bad loop variable" % loop_var.line)
    loop_var = loop_var.text
    p.expect("=")
    lo, lo64, _ = parse_int_literal(p.next())
    p.expect("to")
    hi, hi64, _ = parse_int_literal(p.next())
    if lo64 or hi64:
        raise Error("loop bounds must be int literals")
    p.expect("do")
    p.take_comments()

    env = {"s": "bytes", loop_var: "int"}
    stmts = []  # ("comment", text) | ("let", name, expr) | ("store", offset, expr)
    while True:
        p.peek()  # moves the comments before the next token into p.comments
        for c in p.take_comments():
            stmts.append(("comment", c))
        if p.at("let"):
            p.next()
            name = p.next()
            if name.kind != "ident" or "." in name.text or name.text in env or \
                    name.text in ("s", "load", "store", "round_constants"):
                raise Error("line %d: bad or shadowing let-binding %r" % (name.line, name.text))
            p.expect("=")
            e = ExprParser(p, env, loop_var).expr()
            p.expect("in")
            ty = typecheck(e, env)
            if ty != "int64":
                raise Error("line %d: %s is not an int64" % (name.line, name.text))
            env[name.text] = ty
            stmts.append(("let", name.text, e))
            continue
        t = p.next()
        if t.text != "store":
            raise Error("line %d: expected let or store, found %r" % (t.line, t.text))
        p.expect("s")
        ep = ExprParser(p, env, loop_var)
        off = ep.offset()
        e = ep.atom()
        if typecheck(e, env) != "int64":
            raise Error("line %d: stored value is not int64" % t.line)
        stmts.append(("store", off, e))
        if p.at(";"):
            p.next()
            if p.at("done"):
                break
            continue
        break
    for c in p.take_comments():
        stmts.append(("comment", c))
    p.expect("done")
    if p.peek() is not None:
        t = p.peek()
        raise Error("line %d: unexpected %r after permute" % (t.line, t.text))
    return constants, loop_var, lo, hi, stmts


def generate(src):
    constants, loop_var, lo, hi, stmts = translate(src)
    sha = hashlib.sha256(src.encode("utf-8")).hexdigest()
    stores = [s for s in stmts if s[0] == "store"]
    out = []
    w = out.append
    w("/-")
    w("GENERATED by formal/tools/keccak_to_lean.py from lib/ocaml/keccak.ml; do not edit.")
    w("")
    w("  source: lib/ocaml/keccak.ml, sha256 %s" % sha)
    w("  regenerate: python3 formal/tools/keccak_to_lean.py")
    w("  check:      python3 formal/tools/keccak_to_lean.py --check")
    w("")
    w("The definitions below are a mechanical translation of the parse tree of")
    w("`round_constants` and `permute`: `let x = e in` is `let x := e`,")
    w("`store s i e; rest` is `let s := store s i (e); rest`, and inside")
    w("`let open Lane in` the int64 externals lxor/land/lor/lsl/lsr are")
    w("^^^ / &&& / ||| / <<< / >>> on `BitVec 64` (shift amounts are literals in")
    w("[0, 63], where OCaml's shifts are defined and agree with Lean's). The byte")
    w("buffer is an abstract type `σ`, with `Lane.load` and `Lane.store` as the")
    w("parameters `load` and `store`; KeccakOCaml.lean instantiates them with a")
    w("model of `Lane` on either host endianness and proves `permute` equal to")
    w("the FIPS 202 permutation of Keccak.lean.")
    w("-/")
    w("")
    w("namespace Curve448Formal.KeccakOCamlGen")
    w("")
    w("/-- OCaml's `for i = lo to hi do body done`, threading the state `s`. -/")
    w("def forTo {σ : Type} (lo hi : Nat) (body : Nat → σ → σ) (s : σ) : σ :=")
    w("  go (hi + 1 - lo) lo s")
    w("where")
    w("  go : Nat → Nat → σ → σ")
    w("    | 0, _, s => s")
    w("    | n + 1, i, s => go n (i + 1) (body i s)")
    w("")
    w("/-- `round_constants` (%d int64 literals). -/" % len(constants))
    w("def round_constants : Array (BitVec 64) := #[")
    for k, (value, spelling) in enumerate(constants):
        sep = "," if k + 1 < len(constants) else ""
        w("  %s%s" % (lean_i64(value, spelling), sep))
    w("]")
    w("")
    w("/-- The body of `for %s = %d to %d do ... done` in `permute`. -/" % (loop_var, lo, hi))
    w("def permuteBody {σ : Type} (load : σ → Nat → BitVec 64) (store : σ → Nat → BitVec 64 → σ)")
    w("    (%s : Nat) (s : σ) : σ :=" % loop_var)
    for st in stmts:
        if st[0] == "comment":
            w("  -- %s" % st[1])
        elif st[0] == "let":
            w("  let %s := %s" % (st[1], lean_expr(st[2])))
        else:
            w("  let s := store s %d (%s)" % (st[1], lean_expr(st[2])))
    w("  s")
    w("")
    w("/-- `permute`: the loop `for %s = %d to %d` over `permuteBody`. -/" % (loop_var, lo, hi))
    w("def permute {σ : Type} (load : σ → Nat → BitVec 64) (store : σ → Nat → BitVec 64 → σ)")
    w("    (s : σ) : σ :=")
    w("  forTo %d %d (fun %s s => permuteBody load store %s s) s" % (lo, hi, loop_var, loop_var))
    w("")
    w("/-- Byte offsets of the `store`s in `permuteBody`, in program order. -/")
    w("def storeOffsets : List Nat := [%s]" % ", ".join(str(s[1]) for s in stores))
    w("")
    w("end Curve448Formal.KeccakOCamlGen")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Staleness check of the hand-written C model


C_BEGIN = "-- BEGIN VERBATIM lib/c/native/shake256.h"
C_END = "-- END VERBATIM lib/c/native/shake256.h"


def c_modelled_text(c_src):
    """The part of shake256.h that Keccak.lean models: from the round constant
    table to the end of keccak_f1600 (and the #undef after it)."""
    start = c_src.index("static const uint64_t KECCAK_ROUND_CONSTANTS[24]")
    end = c_src.index("#undef KECCAK_ROTL")
    end = c_src.index("\n", end)
    return c_src[start:end].strip("\n")


def c_tables(text):
    def body(name):
        m = re.search(re.escape(name) + r"\s*\[\s*24\s*\]\s*=\s*\{(.*?)\}\s*;", text, re.S)
        if not m:
            raise Error("table %s not found" % name)
        return m.group(1)
    rc = [int(v, 16) for v in re.findall(r"UINT64_C\(\s*0x([0-9a-fA-F]+)\s*\)",
                                          body("KECCAK_ROUND_CONSTANTS"))]
    rho = [int(v) for v in re.findall(r"\d+", body("KECCAK_RHO"))]
    pi = [int(v) for v in re.findall(r"\d+", body("KECCAK_PI"))]
    return rc, rho, pi


def lean_tables(text):
    def body(name):
        m = re.search(r"def\s+" + re.escape(name) + r"\s*:[^=]*:=\s*\[(.*?)\]", text, re.S)
        if not m:
            raise Error("Lean definition of %s not found in Keccak.lean" % name)
        return m.group(1)
    rc = [int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]+)#64", body("KECCAK_ROUND_CONSTANTS"))]
    rho = [int(v) for v in re.findall(r"\d+", body("KECCAK_RHO"))]
    pi = [int(v) for v in re.findall(r"\d+", body("KECCAK_PI"))]
    return rc, rho, pi


def check_c_model():
    with open(C_SRC, encoding="utf-8") as handle:
        c_src = handle.read()
    with open(LEAN_C_MODEL, encoding="utf-8") as handle:
        lean = handle.read()
    try:
        quoted = lean[lean.index(C_BEGIN) + len(C_BEGIN):lean.index(C_END)].strip("\n")
    except ValueError:
        raise Error("verbatim C quote markers not found in %s" % LEAN_C_MODEL)
    if quoted != c_modelled_text(c_src):
        raise Error("keccak_f1600 in lib/c/native/shake256.h differs from the copy modelled in "
                    "formal/lean/Curve448Formal/Keccak.lean; update the Lean C model")
    if c_tables(c_src) != lean_tables(lean):
        raise Error("the C tables and their Lean definitions in Keccak.lean differ")
    rc, rho, pi = c_tables(c_src)
    if not (len(rc) == len(rho) == len(pi) == 24):
        raise Error("a C table does not have 24 entries")


def main(argv):
    args = argv[1:]
    if args not in ([], ["--check"], ["--stdout"]):
        sys.stderr.write(__doc__)
        return 2
    with open(OCAML_SRC, encoding="utf-8") as handle:
        src = handle.read()
    try:
        text = generate(src)
        if args == ["--check"]:
            check_c_model()
    except Error as e:
        sys.stderr.write("keccak_to_lean: %s\n" % e)
        return 1
    if args == ["--stdout"]:
        sys.stdout.write(text)
        return 0
    if args == ["--check"]:
        try:
            with open(LEAN_OUT, encoding="utf-8") as handle:
                current = handle.read()
        except FileNotFoundError:
            current = None
        if current != text:
            sys.stderr.write("keccak_to_lean: %s is out of date; run "
                             "python3 formal/tools/keccak_to_lean.py\n"
                             % os.path.relpath(LEAN_OUT, ROOT))
            return 1
        return 0
    with open(LEAN_OUT, "w", encoding="utf-8") as handle:
        handle.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
