/-
GENERATED by formal/tools/keccak_to_lean.py from lib/ocaml/keccak.ml; do not edit.

  source: lib/ocaml/keccak.ml, sha256 9521a313aaee3edc7e0cb0c0b68a159210678f3908a18aa8ab31e0d0f7081c78
  regenerate: python3 formal/tools/keccak_to_lean.py
  check:      python3 formal/tools/keccak_to_lean.py --check

The definitions below are a mechanical translation of the parse tree of
`round_constants` and `permute`: `let x = e in` is `let x := e`,
`store s i e; rest` is `let s := store s i (e); rest`, and inside
`let open Lane in` the int64 externals lxor/land/lor/lsl/lsr are
^^^ / &&& / ||| / <<< / >>> on `BitVec 64` (shift amounts are literals in
[0, 63], where OCaml's shifts are defined and agree with Lean's). The byte
buffer is an abstract type `σ`, with `Lane.load` and `Lane.store` as the
parameters `load` and `store`; KeccakOCaml.lean instantiates them with a
model of `Lane` on either host endianness and proves `permute` equal to
the FIPS 202 permutation of Keccak.lean.
-/

namespace Curve448Formal.KeccakOCamlGen

/-- OCaml's `for i = lo to hi do body done`, threading the state `s`. -/
def forTo {σ : Type} (lo hi : Nat) (body : Nat → σ → σ) (s : σ) : σ :=
  go (hi + 1 - lo) lo s
where
  go : Nat → Nat → σ → σ
    | 0, _, s => s
    | n + 1, i, s => go n (i + 1) (body i s)

/-- `round_constants` (24 int64 literals). -/
def round_constants : Array (BitVec 64) := #[
  0x0000000000000001#64,
  0x0000000000008082#64,
  0x800000000000808a#64,
  0x8000000080008000#64,
  0x000000000000808b#64,
  0x0000000080000001#64,
  0x8000000080008081#64,
  0x8000000000008009#64,
  0x000000000000008a#64,
  0x0000000000000088#64,
  0x0000000080008009#64,
  0x000000008000000a#64,
  0x000000008000808b#64,
  0x800000000000008b#64,
  0x8000000000008089#64,
  0x8000000000008003#64,
  0x8000000000008002#64,
  0x8000000000000080#64,
  0x000000000000800a#64,
  0x800000008000000a#64,
  0x8000000080008081#64,
  0x8000000000008080#64,
  0x0000000080000001#64,
  0x8000000080008008#64
]

/-- The body of `for round = 0 to 23 do ... done` in `permute`. -/
def permuteBody {σ : Type} (load : σ → Nat → BitVec 64) (store : σ → Nat → BitVec 64 → σ)
    (round : Nat) (s : σ) : σ :=
  let a00 := load s 0
  let a10 := load s 8
  let a20 := load s 16
  let a30 := load s 24
  let a40 := load s 32
  let a01 := load s 40
  let a11 := load s 48
  let a21 := load s 56
  let a31 := load s 64
  let a41 := load s 72
  let a02 := load s 80
  let a12 := load s 88
  let a22 := load s 96
  let a32 := load s 104
  let a42 := load s 112
  let a03 := load s 120
  let a13 := load s 128
  let a23 := load s 136
  let a33 := load s 144
  let a43 := load s 152
  let a04 := load s 160
  let a14 := load s 168
  let a24 := load s 176
  let a34 := load s 184
  let a44 := load s 192
  -- theta
  let c0 := a00 ^^^ a01 ^^^ a02 ^^^ a03 ^^^ a04
  let c1 := a10 ^^^ a11 ^^^ a12 ^^^ a13 ^^^ a14
  let c2 := a20 ^^^ a21 ^^^ a22 ^^^ a23 ^^^ a24
  let c3 := a30 ^^^ a31 ^^^ a32 ^^^ a33 ^^^ a34
  let c4 := a40 ^^^ a41 ^^^ a42 ^^^ a43 ^^^ a44
  let d0 := c4 ^^^ ((c1 <<< 1) ||| (c1 >>> 63))
  let d1 := c0 ^^^ ((c2 <<< 1) ||| (c2 >>> 63))
  let d2 := c1 ^^^ ((c3 <<< 1) ||| (c3 >>> 63))
  let d3 := c2 ^^^ ((c4 <<< 1) ||| (c4 >>> 63))
  let d4 := c3 ^^^ ((c0 <<< 1) ||| (c0 >>> 63))
  -- rho and pi
  let b00 := a00 ^^^ d0
  let t10 := a10 ^^^ d1
  let b02 := (t10 <<< 1) ||| (t10 >>> 63)
  let t20 := a20 ^^^ d2
  let b04 := (t20 <<< 62) ||| (t20 >>> 2)
  let t30 := a30 ^^^ d3
  let b01 := (t30 <<< 28) ||| (t30 >>> 36)
  let t40 := a40 ^^^ d4
  let b03 := (t40 <<< 27) ||| (t40 >>> 37)
  let t01 := a01 ^^^ d0
  let b13 := (t01 <<< 36) ||| (t01 >>> 28)
  let t11 := a11 ^^^ d1
  let b10 := (t11 <<< 44) ||| (t11 >>> 20)
  let t21 := a21 ^^^ d2
  let b12 := (t21 <<< 6) ||| (t21 >>> 58)
  let t31 := a31 ^^^ d3
  let b14 := (t31 <<< 55) ||| (t31 >>> 9)
  let t41 := a41 ^^^ d4
  let b11 := (t41 <<< 20) ||| (t41 >>> 44)
  let t02 := a02 ^^^ d0
  let b21 := (t02 <<< 3) ||| (t02 >>> 61)
  let t12 := a12 ^^^ d1
  let b23 := (t12 <<< 10) ||| (t12 >>> 54)
  let t22 := a22 ^^^ d2
  let b20 := (t22 <<< 43) ||| (t22 >>> 21)
  let t32 := a32 ^^^ d3
  let b22 := (t32 <<< 25) ||| (t32 >>> 39)
  let t42 := a42 ^^^ d4
  let b24 := (t42 <<< 39) ||| (t42 >>> 25)
  let t03 := a03 ^^^ d0
  let b34 := (t03 <<< 41) ||| (t03 >>> 23)
  let t13 := a13 ^^^ d1
  let b31 := (t13 <<< 45) ||| (t13 >>> 19)
  let t23 := a23 ^^^ d2
  let b33 := (t23 <<< 15) ||| (t23 >>> 49)
  let t33 := a33 ^^^ d3
  let b30 := (t33 <<< 21) ||| (t33 >>> 43)
  let t43 := a43 ^^^ d4
  let b32 := (t43 <<< 8) ||| (t43 >>> 56)
  let t04 := a04 ^^^ d0
  let b42 := (t04 <<< 18) ||| (t04 >>> 46)
  let t14 := a14 ^^^ d1
  let b44 := (t14 <<< 2) ||| (t14 >>> 62)
  let t24 := a24 ^^^ d2
  let b41 := (t24 <<< 61) ||| (t24 >>> 3)
  let t34 := a34 ^^^ d3
  let b43 := (t34 <<< 56) ||| (t34 >>> 8)
  let t44 := a44 ^^^ d4
  let b40 := (t44 <<< 14) ||| (t44 >>> 50)
  -- chi and iota
  let s := store s 0 (b00 ^^^ ((b10 ^^^ (BitVec.ofInt 64 (-1))) &&& b20) ^^^ (round_constants[round]!))
  let s := store s 8 (b10 ^^^ ((b20 ^^^ (BitVec.ofInt 64 (-1))) &&& b30))
  let s := store s 16 (b20 ^^^ ((b30 ^^^ (BitVec.ofInt 64 (-1))) &&& b40))
  let s := store s 24 (b30 ^^^ ((b40 ^^^ (BitVec.ofInt 64 (-1))) &&& b00))
  let s := store s 32 (b40 ^^^ ((b00 ^^^ (BitVec.ofInt 64 (-1))) &&& b10))
  let s := store s 40 (b01 ^^^ ((b11 ^^^ (BitVec.ofInt 64 (-1))) &&& b21))
  let s := store s 48 (b11 ^^^ ((b21 ^^^ (BitVec.ofInt 64 (-1))) &&& b31))
  let s := store s 56 (b21 ^^^ ((b31 ^^^ (BitVec.ofInt 64 (-1))) &&& b41))
  let s := store s 64 (b31 ^^^ ((b41 ^^^ (BitVec.ofInt 64 (-1))) &&& b01))
  let s := store s 72 (b41 ^^^ ((b01 ^^^ (BitVec.ofInt 64 (-1))) &&& b11))
  let s := store s 80 (b02 ^^^ ((b12 ^^^ (BitVec.ofInt 64 (-1))) &&& b22))
  let s := store s 88 (b12 ^^^ ((b22 ^^^ (BitVec.ofInt 64 (-1))) &&& b32))
  let s := store s 96 (b22 ^^^ ((b32 ^^^ (BitVec.ofInt 64 (-1))) &&& b42))
  let s := store s 104 (b32 ^^^ ((b42 ^^^ (BitVec.ofInt 64 (-1))) &&& b02))
  let s := store s 112 (b42 ^^^ ((b02 ^^^ (BitVec.ofInt 64 (-1))) &&& b12))
  let s := store s 120 (b03 ^^^ ((b13 ^^^ (BitVec.ofInt 64 (-1))) &&& b23))
  let s := store s 128 (b13 ^^^ ((b23 ^^^ (BitVec.ofInt 64 (-1))) &&& b33))
  let s := store s 136 (b23 ^^^ ((b33 ^^^ (BitVec.ofInt 64 (-1))) &&& b43))
  let s := store s 144 (b33 ^^^ ((b43 ^^^ (BitVec.ofInt 64 (-1))) &&& b03))
  let s := store s 152 (b43 ^^^ ((b03 ^^^ (BitVec.ofInt 64 (-1))) &&& b13))
  let s := store s 160 (b04 ^^^ ((b14 ^^^ (BitVec.ofInt 64 (-1))) &&& b24))
  let s := store s 168 (b14 ^^^ ((b24 ^^^ (BitVec.ofInt 64 (-1))) &&& b34))
  let s := store s 176 (b24 ^^^ ((b34 ^^^ (BitVec.ofInt 64 (-1))) &&& b44))
  let s := store s 184 (b34 ^^^ ((b44 ^^^ (BitVec.ofInt 64 (-1))) &&& b04))
  let s := store s 192 (b44 ^^^ ((b04 ^^^ (BitVec.ofInt 64 (-1))) &&& b14))
  s

/-- `permute`: the loop `for round = 0 to 23` over `permuteBody`. -/
def permute {σ : Type} (load : σ → Nat → BitVec 64) (store : σ → Nat → BitVec 64 → σ)
    (s : σ) : σ :=
  forTo 0 23 (fun round s => permuteBody load store round s) s

/-- Byte offsets of the `store`s in `permuteBody`, in program order. -/
def storeOffsets : List Nat := [0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192]

end Curve448Formal.KeccakOCamlGen
