/-
Generated by formal/tools/kernels_to_lean.py from lib/ocaml/fe448_kernels.ml; do not edit.

  python3 formal/tools/kernels_to_lean.py           # regenerate
  python3 formal/tools/kernels_to_lean.py --check   # fail if stale

Source sha256: 45bbb1b360bf214fe0a5ef10a4eea46d08bcd29184ff671bb7d229e7297ccdf7

Each kernel's inputs are listed in load order (then int parameters) with
the bound its specification assumes; input j is SSA variable j and
statement j defines SSA variable (number of inputs) + j. The comment on
each statement is the OCaml line it was parsed from.

The generator's own claim (last comment of the OCaml file): mul 2^60.32, sq 2^60.32, add 2^29.58, sub 2^29.58, mul_small 2^44.00, carry 2^29.58.
-/
import Curve448Formal.KernelsAst

namespace Curve448Formal.Kernels

/-- `Fe448_kernels.mul` (int64 arithmetic). -/
def mulK : Kernel where
  name := "mul"
  wide := true
  inputs := [
    (.limb "a" 0, 134217760),  -- 0 a0
    (.limb "a" 1, 134217760),  -- 1 a1
    (.limb "a" 2, 134217760),  -- 2 a2
    (.limb "a" 3, 134217760),  -- 3 a3
    (.limb "a" 4, 134217760),  -- 4 a4
    (.limb "a" 5, 134217760),  -- 5 a5
    (.limb "a" 6, 134217760),  -- 6 a6
    (.limb "a" 7, 134217760),  -- 7 a7
    (.limb "a" 8, 134217760),  -- 8 a8
    (.limb "a" 9, 134217760),  -- 9 a9
    (.limb "a" 10, 134217760),  -- 10 a10
    (.limb "a" 11, 134217760),  -- 11 a11
    (.limb "a" 12, 134217760),  -- 12 a12
    (.limb "a" 13, 134217760),  -- 13 a13
    (.limb "a" 14, 134217760),  -- 14 a14
    (.limb "a" 15, 134217760),  -- 15 a15
    (.limb "b" 0, 134217760),  -- 16 b0
    (.limb "b" 1, 134217760),  -- 17 b1
    (.limb "b" 2, 134217760),  -- 18 b2
    (.limb "b" 3, 134217760),  -- 19 b3
    (.limb "b" 4, 134217760),  -- 20 b4
    (.limb "b" 5, 134217760),  -- 21 b5
    (.limb "b" 6, 134217760),  -- 22 b6
    (.limb "b" 7, 134217760),  -- 23 b7
    (.limb "b" 8, 134217760),  -- 24 b8
    (.limb "b" 9, 134217760),  -- 25 b9
    (.limb "b" 10, 134217760),  -- 26 b10
    (.limb "b" 11, 134217760),  -- 27 b11
    (.limb "b" 12, 134217760),  -- 28 b12
    (.limb "b" 13, 134217760),  -- 29 b13
    (.limb "b" 14, 134217760),  -- 30 b14
    (.limb "b" 15, 134217760)]  -- 31 b15
  names := ["a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "a10", "a11", "a12", "a13", "a14", "a15", "b0", "b1", "b2", "b3", "b4", "b5", "b6", "b7", "b8", "b9", "b10", "b11", "b12", "b13", "b14", "b15", "aa0", "aa1", "aa2", "aa3", "aa4", "aa5", "aa6", "aa7", "bb0", "bb1", "bb2", "bb3", "bb4", "bb5", "bb6", "bb7", "l0", "l1", "l2", "l3", "l4", "l5", "l6", "l7", "l8", "l9", "l10", "l11", "l12", "l13", "l14", "h0", "h1", "h2", "h3", "h4", "h5", "h6", "h7", "h8", "h9", "h10", "h11", "h12", "h13", "h14", "s0", "s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10", "s11", "s12", "s13", "s14", "r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15", "c", "r0", "r1", "c", "r1", "r2", "c", "r2", "r3", "c", "r3", "r4", "c", "r4", "r5", "c", "r5", "r6", "c", "r6", "r7", "c", "r7", "r8", "c", "r8", "r9", "c", "r9", "r10", "c", "r10", "r11", "c", "r11", "r12", "c", "r12", "r13", "c", "r13", "r14", "c", "r14", "r15", "c", "r15", "r0", "r8", "c", "r0", "r1", "c", "r8", "r9"]
  stmts := [
    -- 32: let aa0 = a0 + a8 in
    .add (.var 0) (.var 8),
    -- 33: let aa1 = a1 + a9 in
    .add (.var 1) (.var 9),
    -- 34: let aa2 = a2 + a10 in
    .add (.var 2) (.var 10),
    -- 35: let aa3 = a3 + a11 in
    .add (.var 3) (.var 11),
    -- 36: let aa4 = a4 + a12 in
    .add (.var 4) (.var 12),
    -- 37: let aa5 = a5 + a13 in
    .add (.var 5) (.var 13),
    -- 38: let aa6 = a6 + a14 in
    .add (.var 6) (.var 14),
    -- 39: let aa7 = a7 + a15 in
    .add (.var 7) (.var 15),
    -- 40: let bb0 = b0 + b8 in
    .add (.var 16) (.var 24),
    -- 41: let bb1 = b1 + b9 in
    .add (.var 17) (.var 25),
    -- 42: let bb2 = b2 + b10 in
    .add (.var 18) (.var 26),
    -- 43: let bb3 = b3 + b11 in
    .add (.var 19) (.var 27),
    -- 44: let bb4 = b4 + b12 in
    .add (.var 20) (.var 28),
    -- 45: let bb5 = b5 + b13 in
    .add (.var 21) (.var 29),
    -- 46: let bb6 = b6 + b14 in
    .add (.var 22) (.var 30),
    -- 47: let bb7 = b7 + b15 in
    .add (.var 23) (.var 31),
    -- 48: let l0 = a0 * b0 in
    .mul (.var 0) (.var 16),
    -- 49: let l1 = a0 * b1 + a1 * b0 in
    .add (.mul (.var 0) (.var 17)) (.mul (.var 1) (.var 16)),
    -- 50: let l2 = a0 * b2 + a1 * b1 + a2 * b0 in
    .add (.add (.mul (.var 0) (.var 18)) (.mul (.var 1) (.var 17))) (.mul (.var 2) (.var 16)),
    -- 51: let l3 = a0 * b3 + a1 * b2 + a2 * b1 + a3 * b0 in
    .add (.add (.add (.mul (.var 0) (.var 19)) (.mul (.var 1) (.var 18))) (.mul (.var 2) (.var 17))) (.mul (.var 3) (.var 16)),
    -- 52: let l4 = a0 * b4 + a1 * b3 + a2 * b2 + a3 * b1 + a4 * b0 in
    .add (.add (.add (.add (.mul (.var 0) (.var 20)) (.mul (.var 1) (.var 19))) (.mul (.var 2) (.var 18))) (.mul (.var 3) (.var 17))) (.mul (.var 4) (.var 16)),
    -- 53: let l5 = a0 * b5 + a1 * b4 + a2 * b3 + a3 * b2 + a4 * b1 + a5 * b0 in
    .add (.add (.add (.add (.add (.mul (.var 0) (.var 21)) (.mul (.var 1) (.var 20))) (.mul (.var 2) (.var 19))) (.mul (.var 3) (.var 18))) (.mul (.var 4) (.var 17))) (.mul (.var 5) (.var 16)),
    -- 54: let l6 = a0 * b6 + a1 * b5 + a2 * b4 + a3 * b3 + a4 * b2 + a5 * b1 + a6 * b0 in
    .add (.add (.add (.add (.add (.add (.mul (.var 0) (.var 22)) (.mul (.var 1) (.var 21))) (.mul (.var 2) (.var 20))) (.mul (.var 3) (.var 19))) (.mul (.var 4) (.var 18))) (.mul (.var 5) (.var 17))) (.mul (.var 6) (.var 16)),
    -- 55: let l7 = a0 * b7 + a1 * b6 + a2 * b5 + a3 * b4 + a4 * b3 + a5 * b2 + a6 * b1 + a7 * b0 in
    .add (.add (.add (.add (.add (.add (.add (.mul (.var 0) (.var 23)) (.mul (.var 1) (.var 22))) (.mul (.var 2) (.var 21))) (.mul (.var 3) (.var 20))) (.mul (.var 4) (.var 19))) (.mul (.var 5) (.var 18))) (.mul (.var 6) (.var 17))) (.mul (.var 7) (.var 16)),
    -- 56: let l8 = a1 * b7 + a2 * b6 + a3 * b5 + a4 * b4 + a5 * b3 + a6 * b2 + a7 * b1 in
    .add (.add (.add (.add (.add (.add (.mul (.var 1) (.var 23)) (.mul (.var 2) (.var 22))) (.mul (.var 3) (.var 21))) (.mul (.var 4) (.var 20))) (.mul (.var 5) (.var 19))) (.mul (.var 6) (.var 18))) (.mul (.var 7) (.var 17)),
    -- 57: let l9 = a2 * b7 + a3 * b6 + a4 * b5 + a5 * b4 + a6 * b3 + a7 * b2 in
    .add (.add (.add (.add (.add (.mul (.var 2) (.var 23)) (.mul (.var 3) (.var 22))) (.mul (.var 4) (.var 21))) (.mul (.var 5) (.var 20))) (.mul (.var 6) (.var 19))) (.mul (.var 7) (.var 18)),
    -- 58: let l10 = a3 * b7 + a4 * b6 + a5 * b5 + a6 * b4 + a7 * b3 in
    .add (.add (.add (.add (.mul (.var 3) (.var 23)) (.mul (.var 4) (.var 22))) (.mul (.var 5) (.var 21))) (.mul (.var 6) (.var 20))) (.mul (.var 7) (.var 19)),
    -- 59: let l11 = a4 * b7 + a5 * b6 + a6 * b5 + a7 * b4 in
    .add (.add (.add (.mul (.var 4) (.var 23)) (.mul (.var 5) (.var 22))) (.mul (.var 6) (.var 21))) (.mul (.var 7) (.var 20)),
    -- 60: let l12 = a5 * b7 + a6 * b6 + a7 * b5 in
    .add (.add (.mul (.var 5) (.var 23)) (.mul (.var 6) (.var 22))) (.mul (.var 7) (.var 21)),
    -- 61: let l13 = a6 * b7 + a7 * b6 in
    .add (.mul (.var 6) (.var 23)) (.mul (.var 7) (.var 22)),
    -- 62: let l14 = a7 * b7 in
    .mul (.var 7) (.var 23),
    -- 63: let h0 = a8 * b8 in
    .mul (.var 8) (.var 24),
    -- 64: let h1 = a8 * b9 + a9 * b8 in
    .add (.mul (.var 8) (.var 25)) (.mul (.var 9) (.var 24)),
    -- 65: let h2 = a8 * b10 + a9 * b9 + a10 * b8 in
    .add (.add (.mul (.var 8) (.var 26)) (.mul (.var 9) (.var 25))) (.mul (.var 10) (.var 24)),
    -- 66: let h3 = a8 * b11 + a9 * b10 + a10 * b9 + a11 * b8 in
    .add (.add (.add (.mul (.var 8) (.var 27)) (.mul (.var 9) (.var 26))) (.mul (.var 10) (.var 25))) (.mul (.var 11) (.var 24)),
    -- 67: let h4 = a8 * b12 + a9 * b11 + a10 * b10 + a11 * b9 + a12 * b8 in
    .add (.add (.add (.add (.mul (.var 8) (.var 28)) (.mul (.var 9) (.var 27))) (.mul (.var 10) (.var 26))) (.mul (.var 11) (.var 25))) (.mul (.var 12) (.var 24)),
    -- 68: let h5 = a8 * b13 + a9 * b12 + a10 * b11 + a11 * b10 + a12 * b9 + a13 * b8 in
    .add (.add (.add (.add (.add (.mul (.var 8) (.var 29)) (.mul (.var 9) (.var 28))) (.mul (.var 10) (.var 27))) (.mul (.var 11) (.var 26))) (.mul (.var 12) (.var 25))) (.mul (.var 13) (.var 24)),
    -- 69: let h6 = a8 * b14 + a9 * b13 + a10 * b12 + a11 * b11 + a12 * b10 + a13 * b9 + a14 * b8 in
    .add (.add (.add (.add (.add (.add (.mul (.var 8) (.var 30)) (.mul (.var 9) (.var 29))) (.mul (.var 10) (.var 28))) (.mul (.var 11) (.var 27))) (.mul (.var 12) (.var 26))) (.mul (.var 13) (.var 25))) (.mul (.var 14) (.var 24)),
    -- 70: let h7 = a8 * b15 + a9 * b14 + a10 * b13 + a11 * b12 + a12 * b11 + a13 * b10 + a14 * b9 + a15 * b8 in
    .add (.add (.add (.add (.add (.add (.add (.mul (.var 8) (.var 31)) (.mul (.var 9) (.var 30))) (.mul (.var 10) (.var 29))) (.mul (.var 11) (.var 28))) (.mul (.var 12) (.var 27))) (.mul (.var 13) (.var 26))) (.mul (.var 14) (.var 25))) (.mul (.var 15) (.var 24)),
    -- 71: let h8 = a9 * b15 + a10 * b14 + a11 * b13 + a12 * b12 + a13 * b11 + a14 * b10 + a15 * b9 in
    .add (.add (.add (.add (.add (.add (.mul (.var 9) (.var 31)) (.mul (.var 10) (.var 30))) (.mul (.var 11) (.var 29))) (.mul (.var 12) (.var 28))) (.mul (.var 13) (.var 27))) (.mul (.var 14) (.var 26))) (.mul (.var 15) (.var 25)),
    -- 72: let h9 = a10 * b15 + a11 * b14 + a12 * b13 + a13 * b12 + a14 * b11 + a15 * b10 in
    .add (.add (.add (.add (.add (.mul (.var 10) (.var 31)) (.mul (.var 11) (.var 30))) (.mul (.var 12) (.var 29))) (.mul (.var 13) (.var 28))) (.mul (.var 14) (.var 27))) (.mul (.var 15) (.var 26)),
    -- 73: let h10 = a11 * b15 + a12 * b14 + a13 * b13 + a14 * b12 + a15 * b11 in
    .add (.add (.add (.add (.mul (.var 11) (.var 31)) (.mul (.var 12) (.var 30))) (.mul (.var 13) (.var 29))) (.mul (.var 14) (.var 28))) (.mul (.var 15) (.var 27)),
    -- 74: let h11 = a12 * b15 + a13 * b14 + a14 * b13 + a15 * b12 in
    .add (.add (.add (.mul (.var 12) (.var 31)) (.mul (.var 13) (.var 30))) (.mul (.var 14) (.var 29))) (.mul (.var 15) (.var 28)),
    -- 75: let h12 = a13 * b15 + a14 * b14 + a15 * b13 in
    .add (.add (.mul (.var 13) (.var 31)) (.mul (.var 14) (.var 30))) (.mul (.var 15) (.var 29)),
    -- 76: let h13 = a14 * b15 + a15 * b14 in
    .add (.mul (.var 14) (.var 31)) (.mul (.var 15) (.var 30)),
    -- 77: let h14 = a15 * b15 in
    .mul (.var 15) (.var 31),
    -- 78: let s0 = aa0 * bb0 in
    .mul (.var 32) (.var 40),
    -- 79: let s1 = aa0 * bb1 + aa1 * bb0 in
    .add (.mul (.var 32) (.var 41)) (.mul (.var 33) (.var 40)),
    -- 80: let s2 = aa0 * bb2 + aa1 * bb1 + aa2 * bb0 in
    .add (.add (.mul (.var 32) (.var 42)) (.mul (.var 33) (.var 41))) (.mul (.var 34) (.var 40)),
    -- 81: let s3 = aa0 * bb3 + aa1 * bb2 + aa2 * bb1 + aa3 * bb0 in
    .add (.add (.add (.mul (.var 32) (.var 43)) (.mul (.var 33) (.var 42))) (.mul (.var 34) (.var 41))) (.mul (.var 35) (.var 40)),
    -- 82: let s4 = aa0 * bb4 + aa1 * bb3 + aa2 * bb2 + aa3 * bb1 + aa4 * bb0 in
    .add (.add (.add (.add (.mul (.var 32) (.var 44)) (.mul (.var 33) (.var 43))) (.mul (.var 34) (.var 42))) (.mul (.var 35) (.var 41))) (.mul (.var 36) (.var 40)),
    -- 83: let s5 = aa0 * bb5 + aa1 * bb4 + aa2 * bb3 + aa3 * bb2 + aa4 * bb1 + aa5 * bb0 in
    .add (.add (.add (.add (.add (.mul (.var 32) (.var 45)) (.mul (.var 33) (.var 44))) (.mul (.var 34) (.var 43))) (.mul (.var 35) (.var 42))) (.mul (.var 36) (.var 41))) (.mul (.var 37) (.var 40)),
    -- 84: let s6 = aa0 * bb6 + aa1 * bb5 + aa2 * bb4 + aa3 * bb3 + aa4 * bb2 + aa5 * bb1 + aa6 * bb0 in
    .add (.add (.add (.add (.add (.add (.mul (.var 32) (.var 46)) (.mul (.var 33) (.var 45))) (.mul (.var 34) (.var 44))) (.mul (.var 35) (.var 43))) (.mul (.var 36) (.var 42))) (.mul (.var 37) (.var 41))) (.mul (.var 38) (.var 40)),
    -- 85: let s7 = aa0 * bb7 + aa1 * bb6 + aa2 * bb5 + aa3 * bb4 + aa4 * bb3 + aa5 * bb2 + aa6 * bb1 + aa7 * bb0 in
    .add (.add (.add (.add (.add (.add (.add (.mul (.var 32) (.var 47)) (.mul (.var 33) (.var 46))) (.mul (.var 34) (.var 45))) (.mul (.var 35) (.var 44))) (.mul (.var 36) (.var 43))) (.mul (.var 37) (.var 42))) (.mul (.var 38) (.var 41))) (.mul (.var 39) (.var 40)),
    -- 86: let s8 = aa1 * bb7 + aa2 * bb6 + aa3 * bb5 + aa4 * bb4 + aa5 * bb3 + aa6 * bb2 + aa7 * bb1 in
    .add (.add (.add (.add (.add (.add (.mul (.var 33) (.var 47)) (.mul (.var 34) (.var 46))) (.mul (.var 35) (.var 45))) (.mul (.var 36) (.var 44))) (.mul (.var 37) (.var 43))) (.mul (.var 38) (.var 42))) (.mul (.var 39) (.var 41)),
    -- 87: let s9 = aa2 * bb7 + aa3 * bb6 + aa4 * bb5 + aa5 * bb4 + aa6 * bb3 + aa7 * bb2 in
    .add (.add (.add (.add (.add (.mul (.var 34) (.var 47)) (.mul (.var 35) (.var 46))) (.mul (.var 36) (.var 45))) (.mul (.var 37) (.var 44))) (.mul (.var 38) (.var 43))) (.mul (.var 39) (.var 42)),
    -- 88: let s10 = aa3 * bb7 + aa4 * bb6 + aa5 * bb5 + aa6 * bb4 + aa7 * bb3 in
    .add (.add (.add (.add (.mul (.var 35) (.var 47)) (.mul (.var 36) (.var 46))) (.mul (.var 37) (.var 45))) (.mul (.var 38) (.var 44))) (.mul (.var 39) (.var 43)),
    -- 89: let s11 = aa4 * bb7 + aa5 * bb6 + aa6 * bb5 + aa7 * bb4 in
    .add (.add (.add (.mul (.var 36) (.var 47)) (.mul (.var 37) (.var 46))) (.mul (.var 38) (.var 45))) (.mul (.var 39) (.var 44)),
    -- 90: let s12 = aa5 * bb7 + aa6 * bb6 + aa7 * bb5 in
    .add (.add (.mul (.var 37) (.var 47)) (.mul (.var 38) (.var 46))) (.mul (.var 39) (.var 45)),
    -- 91: let s13 = aa6 * bb7 + aa7 * bb6 in
    .add (.mul (.var 38) (.var 47)) (.mul (.var 39) (.var 46)),
    -- 92: let s14 = aa7 * bb7 in
    .mul (.var 39) (.var 47),
    -- 93: let r0 = l0 + h0 + s8 - l8 in
    .sub (.add (.add (.var 48) (.var 63)) (.var 86)) (.var 56),
    -- 94: let r1 = l1 + h1 + s9 - l9 in
    .sub (.add (.add (.var 49) (.var 64)) (.var 87)) (.var 57),
    -- 95: let r2 = l2 + h2 + s10 - l10 in
    .sub (.add (.add (.var 50) (.var 65)) (.var 88)) (.var 58),
    -- 96: let r3 = l3 + h3 + s11 - l11 in
    .sub (.add (.add (.var 51) (.var 66)) (.var 89)) (.var 59),
    -- 97: let r4 = l4 + h4 + s12 - l12 in
    .sub (.add (.add (.var 52) (.var 67)) (.var 90)) (.var 60),
    -- 98: let r5 = l5 + h5 + s13 - l13 in
    .sub (.add (.add (.var 53) (.var 68)) (.var 91)) (.var 61),
    -- 99: let r6 = l6 + h6 + s14 - l14 in
    .sub (.add (.add (.var 54) (.var 69)) (.var 92)) (.var 62),
    -- 100: let r7 = l7 + h7 in
    .add (.var 55) (.var 70),
    -- 101: let r8 = s0 + h8 + s8 - l0 in
    .sub (.add (.add (.var 78) (.var 71)) (.var 86)) (.var 48),
    -- 102: let r9 = s1 + h9 + s9 - l1 in
    .sub (.add (.add (.var 79) (.var 72)) (.var 87)) (.var 49),
    -- 103: let r10 = s2 + h10 + s10 - l2 in
    .sub (.add (.add (.var 80) (.var 73)) (.var 88)) (.var 50),
    -- 104: let r11 = s3 + h11 + s11 - l3 in
    .sub (.add (.add (.var 81) (.var 74)) (.var 89)) (.var 51),
    -- 105: let r12 = s4 + h12 + s12 - l4 in
    .sub (.add (.add (.var 82) (.var 75)) (.var 90)) (.var 52),
    -- 106: let r13 = s5 + h13 + s13 - l5 in
    .sub (.add (.add (.var 83) (.var 76)) (.var 91)) (.var 53),
    -- 107: let r14 = s6 + h14 + s14 - l6 in
    .sub (.add (.add (.var 84) (.var 77)) (.var 92)) (.var 54),
    -- 108: let r15 = s7 - l7 in
    .sub (.var 85) (.var 55),
    -- 109: let c = (r0 + 0x8000000L) asr 28 in
    .asr (.add (.var 93) (.const 134217728)) 28,
    -- 110: let r0 = r0 - (c lsl 28) in
    .sub (.var 93) (.lsl (.var 109) 28),
    -- 111: let r1 = r1 + c in
    .add (.var 94) (.var 109),
    -- 112: let c = (r1 + 0x8000000L) asr 28 in
    .asr (.add (.var 111) (.const 134217728)) 28,
    -- 113: let r1 = r1 - (c lsl 28) in
    .sub (.var 111) (.lsl (.var 112) 28),
    -- 114: let r2 = r2 + c in
    .add (.var 95) (.var 112),
    -- 115: let c = (r2 + 0x8000000L) asr 28 in
    .asr (.add (.var 114) (.const 134217728)) 28,
    -- 116: let r2 = r2 - (c lsl 28) in
    .sub (.var 114) (.lsl (.var 115) 28),
    -- 117: let r3 = r3 + c in
    .add (.var 96) (.var 115),
    -- 118: let c = (r3 + 0x8000000L) asr 28 in
    .asr (.add (.var 117) (.const 134217728)) 28,
    -- 119: let r3 = r3 - (c lsl 28) in
    .sub (.var 117) (.lsl (.var 118) 28),
    -- 120: let r4 = r4 + c in
    .add (.var 97) (.var 118),
    -- 121: let c = (r4 + 0x8000000L) asr 28 in
    .asr (.add (.var 120) (.const 134217728)) 28,
    -- 122: let r4 = r4 - (c lsl 28) in
    .sub (.var 120) (.lsl (.var 121) 28),
    -- 123: let r5 = r5 + c in
    .add (.var 98) (.var 121),
    -- 124: let c = (r5 + 0x8000000L) asr 28 in
    .asr (.add (.var 123) (.const 134217728)) 28,
    -- 125: let r5 = r5 - (c lsl 28) in
    .sub (.var 123) (.lsl (.var 124) 28),
    -- 126: let r6 = r6 + c in
    .add (.var 99) (.var 124),
    -- 127: let c = (r6 + 0x8000000L) asr 28 in
    .asr (.add (.var 126) (.const 134217728)) 28,
    -- 128: let r6 = r6 - (c lsl 28) in
    .sub (.var 126) (.lsl (.var 127) 28),
    -- 129: let r7 = r7 + c in
    .add (.var 100) (.var 127),
    -- 130: let c = (r7 + 0x8000000L) asr 28 in
    .asr (.add (.var 129) (.const 134217728)) 28,
    -- 131: let r7 = r7 - (c lsl 28) in
    .sub (.var 129) (.lsl (.var 130) 28),
    -- 132: let r8 = r8 + c in
    .add (.var 101) (.var 130),
    -- 133: let c = (r8 + 0x8000000L) asr 28 in
    .asr (.add (.var 132) (.const 134217728)) 28,
    -- 134: let r8 = r8 - (c lsl 28) in
    .sub (.var 132) (.lsl (.var 133) 28),
    -- 135: let r9 = r9 + c in
    .add (.var 102) (.var 133),
    -- 136: let c = (r9 + 0x8000000L) asr 28 in
    .asr (.add (.var 135) (.const 134217728)) 28,
    -- 137: let r9 = r9 - (c lsl 28) in
    .sub (.var 135) (.lsl (.var 136) 28),
    -- 138: let r10 = r10 + c in
    .add (.var 103) (.var 136),
    -- 139: let c = (r10 + 0x8000000L) asr 28 in
    .asr (.add (.var 138) (.const 134217728)) 28,
    -- 140: let r10 = r10 - (c lsl 28) in
    .sub (.var 138) (.lsl (.var 139) 28),
    -- 141: let r11 = r11 + c in
    .add (.var 104) (.var 139),
    -- 142: let c = (r11 + 0x8000000L) asr 28 in
    .asr (.add (.var 141) (.const 134217728)) 28,
    -- 143: let r11 = r11 - (c lsl 28) in
    .sub (.var 141) (.lsl (.var 142) 28),
    -- 144: let r12 = r12 + c in
    .add (.var 105) (.var 142),
    -- 145: let c = (r12 + 0x8000000L) asr 28 in
    .asr (.add (.var 144) (.const 134217728)) 28,
    -- 146: let r12 = r12 - (c lsl 28) in
    .sub (.var 144) (.lsl (.var 145) 28),
    -- 147: let r13 = r13 + c in
    .add (.var 106) (.var 145),
    -- 148: let c = (r13 + 0x8000000L) asr 28 in
    .asr (.add (.var 147) (.const 134217728)) 28,
    -- 149: let r13 = r13 - (c lsl 28) in
    .sub (.var 147) (.lsl (.var 148) 28),
    -- 150: let r14 = r14 + c in
    .add (.var 107) (.var 148),
    -- 151: let c = (r14 + 0x8000000L) asr 28 in
    .asr (.add (.var 150) (.const 134217728)) 28,
    -- 152: let r14 = r14 - (c lsl 28) in
    .sub (.var 150) (.lsl (.var 151) 28),
    -- 153: let r15 = r15 + c in
    .add (.var 108) (.var 151),
    -- 154: let c = (r15 + 0x8000000L) asr 28 in
    .asr (.add (.var 153) (.const 134217728)) 28,
    -- 155: let r15 = r15 - (c lsl 28) in
    .sub (.var 153) (.lsl (.var 154) 28),
    -- 156: let r0 = r0 + c in
    .add (.var 110) (.var 154),
    -- 157: let r8 = r8 + c in
    .add (.var 134) (.var 154),
    -- 158: let c = (r0 + 0x8000000L) asr 28 in
    .asr (.add (.var 156) (.const 134217728)) 28,
    -- 159: let r0 = r0 - (c lsl 28) in
    .sub (.var 156) (.lsl (.var 158) 28),
    -- 160: let r1 = r1 + c in
    .add (.var 113) (.var 158),
    -- 161: let c = (r8 + 0x8000000L) asr 28 in
    .asr (.add (.var 157) (.const 134217728)) 28,
    -- 162: let r8 = r8 - (c lsl 28) in
    .sub (.var 157) (.lsl (.var 161) 28),
    -- 163: let r9 = r9 + c in
    .add (.var 137) (.var 161)]
  outputs := [159, 160, 116, 119, 122, 125, 128, 131, 162, 163, 140, 143, 146, 149, 152, 155]

/-- `Fe448_kernels.sq` (int64 arithmetic). -/
def sqK : Kernel where
  name := "sq"
  wide := true
  inputs := [
    (.limb "a" 0, 134217760),  -- 0 a0
    (.limb "a" 1, 134217760),  -- 1 a1
    (.limb "a" 2, 134217760),  -- 2 a2
    (.limb "a" 3, 134217760),  -- 3 a3
    (.limb "a" 4, 134217760),  -- 4 a4
    (.limb "a" 5, 134217760),  -- 5 a5
    (.limb "a" 6, 134217760),  -- 6 a6
    (.limb "a" 7, 134217760),  -- 7 a7
    (.limb "a" 8, 134217760),  -- 8 a8
    (.limb "a" 9, 134217760),  -- 9 a9
    (.limb "a" 10, 134217760),  -- 10 a10
    (.limb "a" 11, 134217760),  -- 11 a11
    (.limb "a" 12, 134217760),  -- 12 a12
    (.limb "a" 13, 134217760),  -- 13 a13
    (.limb "a" 14, 134217760),  -- 14 a14
    (.limb "a" 15, 134217760)]  -- 15 a15
  names := ["a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "a10", "a11", "a12", "a13", "a14", "a15", "aa0", "aa1", "aa2", "aa3", "aa4", "aa5", "aa6", "aa7", "l0", "da0", "l1", "l2", "da1", "l3", "l4", "da2", "l5", "l6", "da3", "l7", "l8", "da4", "l9", "l10", "da5", "l11", "l12", "da6", "l13", "l14", "h0", "da8", "h1", "h2", "da9", "h3", "h4", "da10", "h5", "h6", "da11", "h7", "h8", "da12", "h9", "h10", "da13", "h11", "h12", "da14", "h13", "h14", "s0", "daa0", "s1", "s2", "daa1", "s3", "s4", "daa2", "s5", "s6", "daa3", "s7", "s8", "daa4", "s9", "s10", "daa5", "s11", "s12", "daa6", "s13", "s14", "r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15", "c", "r0", "r1", "c", "r1", "r2", "c", "r2", "r3", "c", "r3", "r4", "c", "r4", "r5", "c", "r5", "r6", "c", "r6", "r7", "c", "r7", "r8", "c", "r8", "r9", "c", "r9", "r10", "c", "r10", "r11", "c", "r11", "r12", "c", "r12", "r13", "c", "r13", "r14", "c", "r14", "r15", "c", "r15", "r0", "r8", "c", "r0", "r1", "c", "r8", "r9"]
  stmts := [
    -- 16: let aa0 = a0 + a8 in
    .add (.var 0) (.var 8),
    -- 17: let aa1 = a1 + a9 in
    .add (.var 1) (.var 9),
    -- 18: let aa2 = a2 + a10 in
    .add (.var 2) (.var 10),
    -- 19: let aa3 = a3 + a11 in
    .add (.var 3) (.var 11),
    -- 20: let aa4 = a4 + a12 in
    .add (.var 4) (.var 12),
    -- 21: let aa5 = a5 + a13 in
    .add (.var 5) (.var 13),
    -- 22: let aa6 = a6 + a14 in
    .add (.var 6) (.var 14),
    -- 23: let aa7 = a7 + a15 in
    .add (.var 7) (.var 15),
    -- 24: let l0 = a0 * a0 in
    .mul (.var 0) (.var 0),
    -- 25: let da0 = a0 + a0 in
    .add (.var 0) (.var 0),
    -- 26: let l1 = da0 * a1 in
    .mul (.var 25) (.var 1),
    -- 27: let l2 = da0 * a2 + a1 * a1 in
    .add (.mul (.var 25) (.var 2)) (.mul (.var 1) (.var 1)),
    -- 28: let da1 = a1 + a1 in
    .add (.var 1) (.var 1),
    -- 29: let l3 = da0 * a3 + da1 * a2 in
    .add (.mul (.var 25) (.var 3)) (.mul (.var 28) (.var 2)),
    -- 30: let l4 = da0 * a4 + da1 * a3 + a2 * a2 in
    .add (.add (.mul (.var 25) (.var 4)) (.mul (.var 28) (.var 3))) (.mul (.var 2) (.var 2)),
    -- 31: let da2 = a2 + a2 in
    .add (.var 2) (.var 2),
    -- 32: let l5 = da0 * a5 + da1 * a4 + da2 * a3 in
    .add (.add (.mul (.var 25) (.var 5)) (.mul (.var 28) (.var 4))) (.mul (.var 31) (.var 3)),
    -- 33: let l6 = da0 * a6 + da1 * a5 + da2 * a4 + a3 * a3 in
    .add (.add (.add (.mul (.var 25) (.var 6)) (.mul (.var 28) (.var 5))) (.mul (.var 31) (.var 4))) (.mul (.var 3) (.var 3)),
    -- 34: let da3 = a3 + a3 in
    .add (.var 3) (.var 3),
    -- 35: let l7 = da0 * a7 + da1 * a6 + da2 * a5 + da3 * a4 in
    .add (.add (.add (.mul (.var 25) (.var 7)) (.mul (.var 28) (.var 6))) (.mul (.var 31) (.var 5))) (.mul (.var 34) (.var 4)),
    -- 36: let l8 = da1 * a7 + da2 * a6 + da3 * a5 + a4 * a4 in
    .add (.add (.add (.mul (.var 28) (.var 7)) (.mul (.var 31) (.var 6))) (.mul (.var 34) (.var 5))) (.mul (.var 4) (.var 4)),
    -- 37: let da4 = a4 + a4 in
    .add (.var 4) (.var 4),
    -- 38: let l9 = da2 * a7 + da3 * a6 + da4 * a5 in
    .add (.add (.mul (.var 31) (.var 7)) (.mul (.var 34) (.var 6))) (.mul (.var 37) (.var 5)),
    -- 39: let l10 = da3 * a7 + da4 * a6 + a5 * a5 in
    .add (.add (.mul (.var 34) (.var 7)) (.mul (.var 37) (.var 6))) (.mul (.var 5) (.var 5)),
    -- 40: let da5 = a5 + a5 in
    .add (.var 5) (.var 5),
    -- 41: let l11 = da4 * a7 + da5 * a6 in
    .add (.mul (.var 37) (.var 7)) (.mul (.var 40) (.var 6)),
    -- 42: let l12 = da5 * a7 + a6 * a6 in
    .add (.mul (.var 40) (.var 7)) (.mul (.var 6) (.var 6)),
    -- 43: let da6 = a6 + a6 in
    .add (.var 6) (.var 6),
    -- 44: let l13 = da6 * a7 in
    .mul (.var 43) (.var 7),
    -- 45: let l14 = a7 * a7 in
    .mul (.var 7) (.var 7),
    -- 46: let h0 = a8 * a8 in
    .mul (.var 8) (.var 8),
    -- 47: let da8 = a8 + a8 in
    .add (.var 8) (.var 8),
    -- 48: let h1 = da8 * a9 in
    .mul (.var 47) (.var 9),
    -- 49: let h2 = da8 * a10 + a9 * a9 in
    .add (.mul (.var 47) (.var 10)) (.mul (.var 9) (.var 9)),
    -- 50: let da9 = a9 + a9 in
    .add (.var 9) (.var 9),
    -- 51: let h3 = da8 * a11 + da9 * a10 in
    .add (.mul (.var 47) (.var 11)) (.mul (.var 50) (.var 10)),
    -- 52: let h4 = da8 * a12 + da9 * a11 + a10 * a10 in
    .add (.add (.mul (.var 47) (.var 12)) (.mul (.var 50) (.var 11))) (.mul (.var 10) (.var 10)),
    -- 53: let da10 = a10 + a10 in
    .add (.var 10) (.var 10),
    -- 54: let h5 = da8 * a13 + da9 * a12 + da10 * a11 in
    .add (.add (.mul (.var 47) (.var 13)) (.mul (.var 50) (.var 12))) (.mul (.var 53) (.var 11)),
    -- 55: let h6 = da8 * a14 + da9 * a13 + da10 * a12 + a11 * a11 in
    .add (.add (.add (.mul (.var 47) (.var 14)) (.mul (.var 50) (.var 13))) (.mul (.var 53) (.var 12))) (.mul (.var 11) (.var 11)),
    -- 56: let da11 = a11 + a11 in
    .add (.var 11) (.var 11),
    -- 57: let h7 = da8 * a15 + da9 * a14 + da10 * a13 + da11 * a12 in
    .add (.add (.add (.mul (.var 47) (.var 15)) (.mul (.var 50) (.var 14))) (.mul (.var 53) (.var 13))) (.mul (.var 56) (.var 12)),
    -- 58: let h8 = da9 * a15 + da10 * a14 + da11 * a13 + a12 * a12 in
    .add (.add (.add (.mul (.var 50) (.var 15)) (.mul (.var 53) (.var 14))) (.mul (.var 56) (.var 13))) (.mul (.var 12) (.var 12)),
    -- 59: let da12 = a12 + a12 in
    .add (.var 12) (.var 12),
    -- 60: let h9 = da10 * a15 + da11 * a14 + da12 * a13 in
    .add (.add (.mul (.var 53) (.var 15)) (.mul (.var 56) (.var 14))) (.mul (.var 59) (.var 13)),
    -- 61: let h10 = da11 * a15 + da12 * a14 + a13 * a13 in
    .add (.add (.mul (.var 56) (.var 15)) (.mul (.var 59) (.var 14))) (.mul (.var 13) (.var 13)),
    -- 62: let da13 = a13 + a13 in
    .add (.var 13) (.var 13),
    -- 63: let h11 = da12 * a15 + da13 * a14 in
    .add (.mul (.var 59) (.var 15)) (.mul (.var 62) (.var 14)),
    -- 64: let h12 = da13 * a15 + a14 * a14 in
    .add (.mul (.var 62) (.var 15)) (.mul (.var 14) (.var 14)),
    -- 65: let da14 = a14 + a14 in
    .add (.var 14) (.var 14),
    -- 66: let h13 = da14 * a15 in
    .mul (.var 65) (.var 15),
    -- 67: let h14 = a15 * a15 in
    .mul (.var 15) (.var 15),
    -- 68: let s0 = aa0 * aa0 in
    .mul (.var 16) (.var 16),
    -- 69: let daa0 = aa0 + aa0 in
    .add (.var 16) (.var 16),
    -- 70: let s1 = daa0 * aa1 in
    .mul (.var 69) (.var 17),
    -- 71: let s2 = daa0 * aa2 + aa1 * aa1 in
    .add (.mul (.var 69) (.var 18)) (.mul (.var 17) (.var 17)),
    -- 72: let daa1 = aa1 + aa1 in
    .add (.var 17) (.var 17),
    -- 73: let s3 = daa0 * aa3 + daa1 * aa2 in
    .add (.mul (.var 69) (.var 19)) (.mul (.var 72) (.var 18)),
    -- 74: let s4 = daa0 * aa4 + daa1 * aa3 + aa2 * aa2 in
    .add (.add (.mul (.var 69) (.var 20)) (.mul (.var 72) (.var 19))) (.mul (.var 18) (.var 18)),
    -- 75: let daa2 = aa2 + aa2 in
    .add (.var 18) (.var 18),
    -- 76: let s5 = daa0 * aa5 + daa1 * aa4 + daa2 * aa3 in
    .add (.add (.mul (.var 69) (.var 21)) (.mul (.var 72) (.var 20))) (.mul (.var 75) (.var 19)),
    -- 77: let s6 = daa0 * aa6 + daa1 * aa5 + daa2 * aa4 + aa3 * aa3 in
    .add (.add (.add (.mul (.var 69) (.var 22)) (.mul (.var 72) (.var 21))) (.mul (.var 75) (.var 20))) (.mul (.var 19) (.var 19)),
    -- 78: let daa3 = aa3 + aa3 in
    .add (.var 19) (.var 19),
    -- 79: let s7 = daa0 * aa7 + daa1 * aa6 + daa2 * aa5 + daa3 * aa4 in
    .add (.add (.add (.mul (.var 69) (.var 23)) (.mul (.var 72) (.var 22))) (.mul (.var 75) (.var 21))) (.mul (.var 78) (.var 20)),
    -- 80: let s8 = daa1 * aa7 + daa2 * aa6 + daa3 * aa5 + aa4 * aa4 in
    .add (.add (.add (.mul (.var 72) (.var 23)) (.mul (.var 75) (.var 22))) (.mul (.var 78) (.var 21))) (.mul (.var 20) (.var 20)),
    -- 81: let daa4 = aa4 + aa4 in
    .add (.var 20) (.var 20),
    -- 82: let s9 = daa2 * aa7 + daa3 * aa6 + daa4 * aa5 in
    .add (.add (.mul (.var 75) (.var 23)) (.mul (.var 78) (.var 22))) (.mul (.var 81) (.var 21)),
    -- 83: let s10 = daa3 * aa7 + daa4 * aa6 + aa5 * aa5 in
    .add (.add (.mul (.var 78) (.var 23)) (.mul (.var 81) (.var 22))) (.mul (.var 21) (.var 21)),
    -- 84: let daa5 = aa5 + aa5 in
    .add (.var 21) (.var 21),
    -- 85: let s11 = daa4 * aa7 + daa5 * aa6 in
    .add (.mul (.var 81) (.var 23)) (.mul (.var 84) (.var 22)),
    -- 86: let s12 = daa5 * aa7 + aa6 * aa6 in
    .add (.mul (.var 84) (.var 23)) (.mul (.var 22) (.var 22)),
    -- 87: let daa6 = aa6 + aa6 in
    .add (.var 22) (.var 22),
    -- 88: let s13 = daa6 * aa7 in
    .mul (.var 87) (.var 23),
    -- 89: let s14 = aa7 * aa7 in
    .mul (.var 23) (.var 23),
    -- 90: let r0 = l0 + h0 + s8 - l8 in
    .sub (.add (.add (.var 24) (.var 46)) (.var 80)) (.var 36),
    -- 91: let r1 = l1 + h1 + s9 - l9 in
    .sub (.add (.add (.var 26) (.var 48)) (.var 82)) (.var 38),
    -- 92: let r2 = l2 + h2 + s10 - l10 in
    .sub (.add (.add (.var 27) (.var 49)) (.var 83)) (.var 39),
    -- 93: let r3 = l3 + h3 + s11 - l11 in
    .sub (.add (.add (.var 29) (.var 51)) (.var 85)) (.var 41),
    -- 94: let r4 = l4 + h4 + s12 - l12 in
    .sub (.add (.add (.var 30) (.var 52)) (.var 86)) (.var 42),
    -- 95: let r5 = l5 + h5 + s13 - l13 in
    .sub (.add (.add (.var 32) (.var 54)) (.var 88)) (.var 44),
    -- 96: let r6 = l6 + h6 + s14 - l14 in
    .sub (.add (.add (.var 33) (.var 55)) (.var 89)) (.var 45),
    -- 97: let r7 = l7 + h7 in
    .add (.var 35) (.var 57),
    -- 98: let r8 = s0 + h8 + s8 - l0 in
    .sub (.add (.add (.var 68) (.var 58)) (.var 80)) (.var 24),
    -- 99: let r9 = s1 + h9 + s9 - l1 in
    .sub (.add (.add (.var 70) (.var 60)) (.var 82)) (.var 26),
    -- 100: let r10 = s2 + h10 + s10 - l2 in
    .sub (.add (.add (.var 71) (.var 61)) (.var 83)) (.var 27),
    -- 101: let r11 = s3 + h11 + s11 - l3 in
    .sub (.add (.add (.var 73) (.var 63)) (.var 85)) (.var 29),
    -- 102: let r12 = s4 + h12 + s12 - l4 in
    .sub (.add (.add (.var 74) (.var 64)) (.var 86)) (.var 30),
    -- 103: let r13 = s5 + h13 + s13 - l5 in
    .sub (.add (.add (.var 76) (.var 66)) (.var 88)) (.var 32),
    -- 104: let r14 = s6 + h14 + s14 - l6 in
    .sub (.add (.add (.var 77) (.var 67)) (.var 89)) (.var 33),
    -- 105: let r15 = s7 - l7 in
    .sub (.var 79) (.var 35),
    -- 106: let c = (r0 + 0x8000000L) asr 28 in
    .asr (.add (.var 90) (.const 134217728)) 28,
    -- 107: let r0 = r0 - (c lsl 28) in
    .sub (.var 90) (.lsl (.var 106) 28),
    -- 108: let r1 = r1 + c in
    .add (.var 91) (.var 106),
    -- 109: let c = (r1 + 0x8000000L) asr 28 in
    .asr (.add (.var 108) (.const 134217728)) 28,
    -- 110: let r1 = r1 - (c lsl 28) in
    .sub (.var 108) (.lsl (.var 109) 28),
    -- 111: let r2 = r2 + c in
    .add (.var 92) (.var 109),
    -- 112: let c = (r2 + 0x8000000L) asr 28 in
    .asr (.add (.var 111) (.const 134217728)) 28,
    -- 113: let r2 = r2 - (c lsl 28) in
    .sub (.var 111) (.lsl (.var 112) 28),
    -- 114: let r3 = r3 + c in
    .add (.var 93) (.var 112),
    -- 115: let c = (r3 + 0x8000000L) asr 28 in
    .asr (.add (.var 114) (.const 134217728)) 28,
    -- 116: let r3 = r3 - (c lsl 28) in
    .sub (.var 114) (.lsl (.var 115) 28),
    -- 117: let r4 = r4 + c in
    .add (.var 94) (.var 115),
    -- 118: let c = (r4 + 0x8000000L) asr 28 in
    .asr (.add (.var 117) (.const 134217728)) 28,
    -- 119: let r4 = r4 - (c lsl 28) in
    .sub (.var 117) (.lsl (.var 118) 28),
    -- 120: let r5 = r5 + c in
    .add (.var 95) (.var 118),
    -- 121: let c = (r5 + 0x8000000L) asr 28 in
    .asr (.add (.var 120) (.const 134217728)) 28,
    -- 122: let r5 = r5 - (c lsl 28) in
    .sub (.var 120) (.lsl (.var 121) 28),
    -- 123: let r6 = r6 + c in
    .add (.var 96) (.var 121),
    -- 124: let c = (r6 + 0x8000000L) asr 28 in
    .asr (.add (.var 123) (.const 134217728)) 28,
    -- 125: let r6 = r6 - (c lsl 28) in
    .sub (.var 123) (.lsl (.var 124) 28),
    -- 126: let r7 = r7 + c in
    .add (.var 97) (.var 124),
    -- 127: let c = (r7 + 0x8000000L) asr 28 in
    .asr (.add (.var 126) (.const 134217728)) 28,
    -- 128: let r7 = r7 - (c lsl 28) in
    .sub (.var 126) (.lsl (.var 127) 28),
    -- 129: let r8 = r8 + c in
    .add (.var 98) (.var 127),
    -- 130: let c = (r8 + 0x8000000L) asr 28 in
    .asr (.add (.var 129) (.const 134217728)) 28,
    -- 131: let r8 = r8 - (c lsl 28) in
    .sub (.var 129) (.lsl (.var 130) 28),
    -- 132: let r9 = r9 + c in
    .add (.var 99) (.var 130),
    -- 133: let c = (r9 + 0x8000000L) asr 28 in
    .asr (.add (.var 132) (.const 134217728)) 28,
    -- 134: let r9 = r9 - (c lsl 28) in
    .sub (.var 132) (.lsl (.var 133) 28),
    -- 135: let r10 = r10 + c in
    .add (.var 100) (.var 133),
    -- 136: let c = (r10 + 0x8000000L) asr 28 in
    .asr (.add (.var 135) (.const 134217728)) 28,
    -- 137: let r10 = r10 - (c lsl 28) in
    .sub (.var 135) (.lsl (.var 136) 28),
    -- 138: let r11 = r11 + c in
    .add (.var 101) (.var 136),
    -- 139: let c = (r11 + 0x8000000L) asr 28 in
    .asr (.add (.var 138) (.const 134217728)) 28,
    -- 140: let r11 = r11 - (c lsl 28) in
    .sub (.var 138) (.lsl (.var 139) 28),
    -- 141: let r12 = r12 + c in
    .add (.var 102) (.var 139),
    -- 142: let c = (r12 + 0x8000000L) asr 28 in
    .asr (.add (.var 141) (.const 134217728)) 28,
    -- 143: let r12 = r12 - (c lsl 28) in
    .sub (.var 141) (.lsl (.var 142) 28),
    -- 144: let r13 = r13 + c in
    .add (.var 103) (.var 142),
    -- 145: let c = (r13 + 0x8000000L) asr 28 in
    .asr (.add (.var 144) (.const 134217728)) 28,
    -- 146: let r13 = r13 - (c lsl 28) in
    .sub (.var 144) (.lsl (.var 145) 28),
    -- 147: let r14 = r14 + c in
    .add (.var 104) (.var 145),
    -- 148: let c = (r14 + 0x8000000L) asr 28 in
    .asr (.add (.var 147) (.const 134217728)) 28,
    -- 149: let r14 = r14 - (c lsl 28) in
    .sub (.var 147) (.lsl (.var 148) 28),
    -- 150: let r15 = r15 + c in
    .add (.var 105) (.var 148),
    -- 151: let c = (r15 + 0x8000000L) asr 28 in
    .asr (.add (.var 150) (.const 134217728)) 28,
    -- 152: let r15 = r15 - (c lsl 28) in
    .sub (.var 150) (.lsl (.var 151) 28),
    -- 153: let r0 = r0 + c in
    .add (.var 107) (.var 151),
    -- 154: let r8 = r8 + c in
    .add (.var 131) (.var 151),
    -- 155: let c = (r0 + 0x8000000L) asr 28 in
    .asr (.add (.var 153) (.const 134217728)) 28,
    -- 156: let r0 = r0 - (c lsl 28) in
    .sub (.var 153) (.lsl (.var 155) 28),
    -- 157: let r1 = r1 + c in
    .add (.var 110) (.var 155),
    -- 158: let c = (r8 + 0x8000000L) asr 28 in
    .asr (.add (.var 154) (.const 134217728)) 28,
    -- 159: let r8 = r8 - (c lsl 28) in
    .sub (.var 154) (.lsl (.var 158) 28),
    -- 160: let r9 = r9 + c in
    .add (.var 134) (.var 158)]
  outputs := [156, 157, 113, 116, 119, 122, 125, 128, 159, 160, 137, 140, 143, 146, 149, 152]

/-- `Fe448_kernels.add` (OCaml int arithmetic). -/
def addK : Kernel where
  name := "add"
  wide := false
  inputs := [
    (.limb "a" 0, 134217760),  -- 0 a0
    (.limb "a" 1, 134217760),  -- 1 a1
    (.limb "a" 2, 134217760),  -- 2 a2
    (.limb "a" 3, 134217760),  -- 3 a3
    (.limb "a" 4, 134217760),  -- 4 a4
    (.limb "a" 5, 134217760),  -- 5 a5
    (.limb "a" 6, 134217760),  -- 6 a6
    (.limb "a" 7, 134217760),  -- 7 a7
    (.limb "a" 8, 134217760),  -- 8 a8
    (.limb "a" 9, 134217760),  -- 9 a9
    (.limb "a" 10, 134217760),  -- 10 a10
    (.limb "a" 11, 134217760),  -- 11 a11
    (.limb "a" 12, 134217760),  -- 12 a12
    (.limb "a" 13, 134217760),  -- 13 a13
    (.limb "a" 14, 134217760),  -- 14 a14
    (.limb "a" 15, 134217760),  -- 15 a15
    (.limb "b" 0, 134217760),  -- 16 b0
    (.limb "b" 1, 134217760),  -- 17 b1
    (.limb "b" 2, 134217760),  -- 18 b2
    (.limb "b" 3, 134217760),  -- 19 b3
    (.limb "b" 4, 134217760),  -- 20 b4
    (.limb "b" 5, 134217760),  -- 21 b5
    (.limb "b" 6, 134217760),  -- 22 b6
    (.limb "b" 7, 134217760),  -- 23 b7
    (.limb "b" 8, 134217760),  -- 24 b8
    (.limb "b" 9, 134217760),  -- 25 b9
    (.limb "b" 10, 134217760),  -- 26 b10
    (.limb "b" 11, 134217760),  -- 27 b11
    (.limb "b" 12, 134217760),  -- 28 b12
    (.limb "b" 13, 134217760),  -- 29 b13
    (.limb "b" 14, 134217760),  -- 30 b14
    (.limb "b" 15, 134217760)]  -- 31 b15
  names := ["a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "a10", "a11", "a12", "a13", "a14", "a15", "b0", "b1", "b2", "b3", "b4", "b5", "b6", "b7", "b8", "b9", "b10", "b11", "b12", "b13", "b14", "b15", "x0", "x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "c0", "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10", "c11", "c12", "c13", "c14", "c15", "q0", "q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9", "q10", "q11", "q12", "q13", "q14", "q15", "r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15"]
  stmts := [
    -- 32: let x0 = a0 + b0 in
    .add (.var 0) (.var 16),
    -- 33: let x1 = a1 + b1 in
    .add (.var 1) (.var 17),
    -- 34: let x2 = a2 + b2 in
    .add (.var 2) (.var 18),
    -- 35: let x3 = a3 + b3 in
    .add (.var 3) (.var 19),
    -- 36: let x4 = a4 + b4 in
    .add (.var 4) (.var 20),
    -- 37: let x5 = a5 + b5 in
    .add (.var 5) (.var 21),
    -- 38: let x6 = a6 + b6 in
    .add (.var 6) (.var 22),
    -- 39: let x7 = a7 + b7 in
    .add (.var 7) (.var 23),
    -- 40: let x8 = a8 + b8 in
    .add (.var 8) (.var 24),
    -- 41: let x9 = a9 + b9 in
    .add (.var 9) (.var 25),
    -- 42: let x10 = a10 + b10 in
    .add (.var 10) (.var 26),
    -- 43: let x11 = a11 + b11 in
    .add (.var 11) (.var 27),
    -- 44: let x12 = a12 + b12 in
    .add (.var 12) (.var 28),
    -- 45: let x13 = a13 + b13 in
    .add (.var 13) (.var 29),
    -- 46: let x14 = a14 + b14 in
    .add (.var 14) (.var 30),
    -- 47: let x15 = a15 + b15 in
    .add (.var 15) (.var 31),
    -- 48: let c0 = (x0 + 0x8000000) asr 28 in
    .asr (.add (.var 32) (.const 134217728)) 28,
    -- 49: let c1 = (x1 + 0x8000000) asr 28 in
    .asr (.add (.var 33) (.const 134217728)) 28,
    -- 50: let c2 = (x2 + 0x8000000) asr 28 in
    .asr (.add (.var 34) (.const 134217728)) 28,
    -- 51: let c3 = (x3 + 0x8000000) asr 28 in
    .asr (.add (.var 35) (.const 134217728)) 28,
    -- 52: let c4 = (x4 + 0x8000000) asr 28 in
    .asr (.add (.var 36) (.const 134217728)) 28,
    -- 53: let c5 = (x5 + 0x8000000) asr 28 in
    .asr (.add (.var 37) (.const 134217728)) 28,
    -- 54: let c6 = (x6 + 0x8000000) asr 28 in
    .asr (.add (.var 38) (.const 134217728)) 28,
    -- 55: let c7 = (x7 + 0x8000000) asr 28 in
    .asr (.add (.var 39) (.const 134217728)) 28,
    -- 56: let c8 = (x8 + 0x8000000) asr 28 in
    .asr (.add (.var 40) (.const 134217728)) 28,
    -- 57: let c9 = (x9 + 0x8000000) asr 28 in
    .asr (.add (.var 41) (.const 134217728)) 28,
    -- 58: let c10 = (x10 + 0x8000000) asr 28 in
    .asr (.add (.var 42) (.const 134217728)) 28,
    -- 59: let c11 = (x11 + 0x8000000) asr 28 in
    .asr (.add (.var 43) (.const 134217728)) 28,
    -- 60: let c12 = (x12 + 0x8000000) asr 28 in
    .asr (.add (.var 44) (.const 134217728)) 28,
    -- 61: let c13 = (x13 + 0x8000000) asr 28 in
    .asr (.add (.var 45) (.const 134217728)) 28,
    -- 62: let c14 = (x14 + 0x8000000) asr 28 in
    .asr (.add (.var 46) (.const 134217728)) 28,
    -- 63: let c15 = (x15 + 0x8000000) asr 28 in
    .asr (.add (.var 47) (.const 134217728)) 28,
    -- 64: let q0 = x0 - (c0 lsl 28) in
    .sub (.var 32) (.lsl (.var 48) 28),
    -- 65: let q1 = x1 - (c1 lsl 28) in
    .sub (.var 33) (.lsl (.var 49) 28),
    -- 66: let q2 = x2 - (c2 lsl 28) in
    .sub (.var 34) (.lsl (.var 50) 28),
    -- 67: let q3 = x3 - (c3 lsl 28) in
    .sub (.var 35) (.lsl (.var 51) 28),
    -- 68: let q4 = x4 - (c4 lsl 28) in
    .sub (.var 36) (.lsl (.var 52) 28),
    -- 69: let q5 = x5 - (c5 lsl 28) in
    .sub (.var 37) (.lsl (.var 53) 28),
    -- 70: let q6 = x6 - (c6 lsl 28) in
    .sub (.var 38) (.lsl (.var 54) 28),
    -- 71: let q7 = x7 - (c7 lsl 28) in
    .sub (.var 39) (.lsl (.var 55) 28),
    -- 72: let q8 = x8 - (c8 lsl 28) in
    .sub (.var 40) (.lsl (.var 56) 28),
    -- 73: let q9 = x9 - (c9 lsl 28) in
    .sub (.var 41) (.lsl (.var 57) 28),
    -- 74: let q10 = x10 - (c10 lsl 28) in
    .sub (.var 42) (.lsl (.var 58) 28),
    -- 75: let q11 = x11 - (c11 lsl 28) in
    .sub (.var 43) (.lsl (.var 59) 28),
    -- 76: let q12 = x12 - (c12 lsl 28) in
    .sub (.var 44) (.lsl (.var 60) 28),
    -- 77: let q13 = x13 - (c13 lsl 28) in
    .sub (.var 45) (.lsl (.var 61) 28),
    -- 78: let q14 = x14 - (c14 lsl 28) in
    .sub (.var 46) (.lsl (.var 62) 28),
    -- 79: let q15 = x15 - (c15 lsl 28) in
    .sub (.var 47) (.lsl (.var 63) 28),
    -- 80: let r0 = q0 + c15 in
    .add (.var 64) (.var 63),
    -- 81: let r1 = q1 + c0 in
    .add (.var 65) (.var 48),
    -- 82: let r2 = q2 + c1 in
    .add (.var 66) (.var 49),
    -- 83: let r3 = q3 + c2 in
    .add (.var 67) (.var 50),
    -- 84: let r4 = q4 + c3 in
    .add (.var 68) (.var 51),
    -- 85: let r5 = q5 + c4 in
    .add (.var 69) (.var 52),
    -- 86: let r6 = q6 + c5 in
    .add (.var 70) (.var 53),
    -- 87: let r7 = q7 + c6 in
    .add (.var 71) (.var 54),
    -- 88: let r8 = q8 + c7 + c15 in
    .add (.add (.var 72) (.var 55)) (.var 63),
    -- 89: let r9 = q9 + c8 in
    .add (.var 73) (.var 56),
    -- 90: let r10 = q10 + c9 in
    .add (.var 74) (.var 57),
    -- 91: let r11 = q11 + c10 in
    .add (.var 75) (.var 58),
    -- 92: let r12 = q12 + c11 in
    .add (.var 76) (.var 59),
    -- 93: let r13 = q13 + c12 in
    .add (.var 77) (.var 60),
    -- 94: let r14 = q14 + c13 in
    .add (.var 78) (.var 61),
    -- 95: let r15 = q15 + c14 in
    .add (.var 79) (.var 62)]
  outputs := [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]

/-- `Fe448_kernels.sub` (OCaml int arithmetic). -/
def subK : Kernel where
  name := "sub"
  wide := false
  inputs := [
    (.limb "a" 0, 134217760),  -- 0 a0
    (.limb "a" 1, 134217760),  -- 1 a1
    (.limb "a" 2, 134217760),  -- 2 a2
    (.limb "a" 3, 134217760),  -- 3 a3
    (.limb "a" 4, 134217760),  -- 4 a4
    (.limb "a" 5, 134217760),  -- 5 a5
    (.limb "a" 6, 134217760),  -- 6 a6
    (.limb "a" 7, 134217760),  -- 7 a7
    (.limb "a" 8, 134217760),  -- 8 a8
    (.limb "a" 9, 134217760),  -- 9 a9
    (.limb "a" 10, 134217760),  -- 10 a10
    (.limb "a" 11, 134217760),  -- 11 a11
    (.limb "a" 12, 134217760),  -- 12 a12
    (.limb "a" 13, 134217760),  -- 13 a13
    (.limb "a" 14, 134217760),  -- 14 a14
    (.limb "a" 15, 134217760),  -- 15 a15
    (.limb "b" 0, 134217760),  -- 16 b0
    (.limb "b" 1, 134217760),  -- 17 b1
    (.limb "b" 2, 134217760),  -- 18 b2
    (.limb "b" 3, 134217760),  -- 19 b3
    (.limb "b" 4, 134217760),  -- 20 b4
    (.limb "b" 5, 134217760),  -- 21 b5
    (.limb "b" 6, 134217760),  -- 22 b6
    (.limb "b" 7, 134217760),  -- 23 b7
    (.limb "b" 8, 134217760),  -- 24 b8
    (.limb "b" 9, 134217760),  -- 25 b9
    (.limb "b" 10, 134217760),  -- 26 b10
    (.limb "b" 11, 134217760),  -- 27 b11
    (.limb "b" 12, 134217760),  -- 28 b12
    (.limb "b" 13, 134217760),  -- 29 b13
    (.limb "b" 14, 134217760),  -- 30 b14
    (.limb "b" 15, 134217760)]  -- 31 b15
  names := ["a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "a10", "a11", "a12", "a13", "a14", "a15", "b0", "b1", "b2", "b3", "b4", "b5", "b6", "b7", "b8", "b9", "b10", "b11", "b12", "b13", "b14", "b15", "x0", "x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "c0", "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10", "c11", "c12", "c13", "c14", "c15", "q0", "q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9", "q10", "q11", "q12", "q13", "q14", "q15", "r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15"]
  stmts := [
    -- 32: let x0 = a0 - b0 in
    .sub (.var 0) (.var 16),
    -- 33: let x1 = a1 - b1 in
    .sub (.var 1) (.var 17),
    -- 34: let x2 = a2 - b2 in
    .sub (.var 2) (.var 18),
    -- 35: let x3 = a3 - b3 in
    .sub (.var 3) (.var 19),
    -- 36: let x4 = a4 - b4 in
    .sub (.var 4) (.var 20),
    -- 37: let x5 = a5 - b5 in
    .sub (.var 5) (.var 21),
    -- 38: let x6 = a6 - b6 in
    .sub (.var 6) (.var 22),
    -- 39: let x7 = a7 - b7 in
    .sub (.var 7) (.var 23),
    -- 40: let x8 = a8 - b8 in
    .sub (.var 8) (.var 24),
    -- 41: let x9 = a9 - b9 in
    .sub (.var 9) (.var 25),
    -- 42: let x10 = a10 - b10 in
    .sub (.var 10) (.var 26),
    -- 43: let x11 = a11 - b11 in
    .sub (.var 11) (.var 27),
    -- 44: let x12 = a12 - b12 in
    .sub (.var 12) (.var 28),
    -- 45: let x13 = a13 - b13 in
    .sub (.var 13) (.var 29),
    -- 46: let x14 = a14 - b14 in
    .sub (.var 14) (.var 30),
    -- 47: let x15 = a15 - b15 in
    .sub (.var 15) (.var 31),
    -- 48: let c0 = (x0 + 0x8000000) asr 28 in
    .asr (.add (.var 32) (.const 134217728)) 28,
    -- 49: let c1 = (x1 + 0x8000000) asr 28 in
    .asr (.add (.var 33) (.const 134217728)) 28,
    -- 50: let c2 = (x2 + 0x8000000) asr 28 in
    .asr (.add (.var 34) (.const 134217728)) 28,
    -- 51: let c3 = (x3 + 0x8000000) asr 28 in
    .asr (.add (.var 35) (.const 134217728)) 28,
    -- 52: let c4 = (x4 + 0x8000000) asr 28 in
    .asr (.add (.var 36) (.const 134217728)) 28,
    -- 53: let c5 = (x5 + 0x8000000) asr 28 in
    .asr (.add (.var 37) (.const 134217728)) 28,
    -- 54: let c6 = (x6 + 0x8000000) asr 28 in
    .asr (.add (.var 38) (.const 134217728)) 28,
    -- 55: let c7 = (x7 + 0x8000000) asr 28 in
    .asr (.add (.var 39) (.const 134217728)) 28,
    -- 56: let c8 = (x8 + 0x8000000) asr 28 in
    .asr (.add (.var 40) (.const 134217728)) 28,
    -- 57: let c9 = (x9 + 0x8000000) asr 28 in
    .asr (.add (.var 41) (.const 134217728)) 28,
    -- 58: let c10 = (x10 + 0x8000000) asr 28 in
    .asr (.add (.var 42) (.const 134217728)) 28,
    -- 59: let c11 = (x11 + 0x8000000) asr 28 in
    .asr (.add (.var 43) (.const 134217728)) 28,
    -- 60: let c12 = (x12 + 0x8000000) asr 28 in
    .asr (.add (.var 44) (.const 134217728)) 28,
    -- 61: let c13 = (x13 + 0x8000000) asr 28 in
    .asr (.add (.var 45) (.const 134217728)) 28,
    -- 62: let c14 = (x14 + 0x8000000) asr 28 in
    .asr (.add (.var 46) (.const 134217728)) 28,
    -- 63: let c15 = (x15 + 0x8000000) asr 28 in
    .asr (.add (.var 47) (.const 134217728)) 28,
    -- 64: let q0 = x0 - (c0 lsl 28) in
    .sub (.var 32) (.lsl (.var 48) 28),
    -- 65: let q1 = x1 - (c1 lsl 28) in
    .sub (.var 33) (.lsl (.var 49) 28),
    -- 66: let q2 = x2 - (c2 lsl 28) in
    .sub (.var 34) (.lsl (.var 50) 28),
    -- 67: let q3 = x3 - (c3 lsl 28) in
    .sub (.var 35) (.lsl (.var 51) 28),
    -- 68: let q4 = x4 - (c4 lsl 28) in
    .sub (.var 36) (.lsl (.var 52) 28),
    -- 69: let q5 = x5 - (c5 lsl 28) in
    .sub (.var 37) (.lsl (.var 53) 28),
    -- 70: let q6 = x6 - (c6 lsl 28) in
    .sub (.var 38) (.lsl (.var 54) 28),
    -- 71: let q7 = x7 - (c7 lsl 28) in
    .sub (.var 39) (.lsl (.var 55) 28),
    -- 72: let q8 = x8 - (c8 lsl 28) in
    .sub (.var 40) (.lsl (.var 56) 28),
    -- 73: let q9 = x9 - (c9 lsl 28) in
    .sub (.var 41) (.lsl (.var 57) 28),
    -- 74: let q10 = x10 - (c10 lsl 28) in
    .sub (.var 42) (.lsl (.var 58) 28),
    -- 75: let q11 = x11 - (c11 lsl 28) in
    .sub (.var 43) (.lsl (.var 59) 28),
    -- 76: let q12 = x12 - (c12 lsl 28) in
    .sub (.var 44) (.lsl (.var 60) 28),
    -- 77: let q13 = x13 - (c13 lsl 28) in
    .sub (.var 45) (.lsl (.var 61) 28),
    -- 78: let q14 = x14 - (c14 lsl 28) in
    .sub (.var 46) (.lsl (.var 62) 28),
    -- 79: let q15 = x15 - (c15 lsl 28) in
    .sub (.var 47) (.lsl (.var 63) 28),
    -- 80: let r0 = q0 + c15 in
    .add (.var 64) (.var 63),
    -- 81: let r1 = q1 + c0 in
    .add (.var 65) (.var 48),
    -- 82: let r2 = q2 + c1 in
    .add (.var 66) (.var 49),
    -- 83: let r3 = q3 + c2 in
    .add (.var 67) (.var 50),
    -- 84: let r4 = q4 + c3 in
    .add (.var 68) (.var 51),
    -- 85: let r5 = q5 + c4 in
    .add (.var 69) (.var 52),
    -- 86: let r6 = q6 + c5 in
    .add (.var 70) (.var 53),
    -- 87: let r7 = q7 + c6 in
    .add (.var 71) (.var 54),
    -- 88: let r8 = q8 + c7 + c15 in
    .add (.add (.var 72) (.var 55)) (.var 63),
    -- 89: let r9 = q9 + c8 in
    .add (.var 73) (.var 56),
    -- 90: let r10 = q10 + c9 in
    .add (.var 74) (.var 57),
    -- 91: let r11 = q11 + c10 in
    .add (.var 75) (.var 58),
    -- 92: let r12 = q12 + c11 in
    .add (.var 76) (.var 59),
    -- 93: let r13 = q13 + c12 in
    .add (.var 77) (.var 60),
    -- 94: let r14 = q14 + c13 in
    .add (.var 78) (.var 61),
    -- 95: let r15 = q15 + c14 in
    .add (.var 79) (.var 62)]
  outputs := [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]

/-- `Fe448_kernels.mul_small` (OCaml int arithmetic). -/
def mulSmallK : Kernel where
  name := "mul_small"
  wide := false
  inputs := [
    (.limb "a" 0, 134217760),  -- 0 a0
    (.limb "a" 1, 134217760),  -- 1 a1
    (.limb "a" 2, 134217760),  -- 2 a2
    (.limb "a" 3, 134217760),  -- 3 a3
    (.limb "a" 4, 134217760),  -- 4 a4
    (.limb "a" 5, 134217760),  -- 5 a5
    (.limb "a" 6, 134217760),  -- 6 a6
    (.limb "a" 7, 134217760),  -- 7 a7
    (.limb "a" 8, 134217760),  -- 8 a8
    (.limb "a" 9, 134217760),  -- 9 a9
    (.limb "a" 10, 134217760),  -- 10 a10
    (.limb "a" 11, 134217760),  -- 11 a11
    (.limb "a" 12, 134217760),  -- 12 a12
    (.limb "a" 13, 134217760),  -- 13 a13
    (.limb "a" 14, 134217760),  -- 14 a14
    (.limb "a" 15, 134217760),  -- 15 a15
    (.scalar "k", 65536)]  -- 16 k
  names := ["a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "a10", "a11", "a12", "a13", "a14", "a15", "k", "x0", "x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "c0", "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10", "c11", "c12", "c13", "c14", "c15", "q0", "q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9", "q10", "q11", "q12", "q13", "q14", "q15", "y0", "y1", "y2", "y3", "y4", "y5", "y6", "y7", "y8", "y9", "y10", "y11", "y12", "y13", "y14", "y15", "d0", "d1", "d2", "d3", "d4", "d5", "d6", "d7", "d8", "d9", "d10", "d11", "d12", "d13", "d14", "d15", "e0", "e1", "e2", "e3", "e4", "e5", "e6", "e7", "e8", "e9", "e10", "e11", "e12", "e13", "e14", "e15", "r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15"]
  stmts := [
    -- 17: let x0 = a0 * k in
    .mul (.var 0) (.var 16),
    -- 18: let x1 = a1 * k in
    .mul (.var 1) (.var 16),
    -- 19: let x2 = a2 * k in
    .mul (.var 2) (.var 16),
    -- 20: let x3 = a3 * k in
    .mul (.var 3) (.var 16),
    -- 21: let x4 = a4 * k in
    .mul (.var 4) (.var 16),
    -- 22: let x5 = a5 * k in
    .mul (.var 5) (.var 16),
    -- 23: let x6 = a6 * k in
    .mul (.var 6) (.var 16),
    -- 24: let x7 = a7 * k in
    .mul (.var 7) (.var 16),
    -- 25: let x8 = a8 * k in
    .mul (.var 8) (.var 16),
    -- 26: let x9 = a9 * k in
    .mul (.var 9) (.var 16),
    -- 27: let x10 = a10 * k in
    .mul (.var 10) (.var 16),
    -- 28: let x11 = a11 * k in
    .mul (.var 11) (.var 16),
    -- 29: let x12 = a12 * k in
    .mul (.var 12) (.var 16),
    -- 30: let x13 = a13 * k in
    .mul (.var 13) (.var 16),
    -- 31: let x14 = a14 * k in
    .mul (.var 14) (.var 16),
    -- 32: let x15 = a15 * k in
    .mul (.var 15) (.var 16),
    -- 33: let c0 = (x0 + 0x8000000) asr 28 in
    .asr (.add (.var 17) (.const 134217728)) 28,
    -- 34: let c1 = (x1 + 0x8000000) asr 28 in
    .asr (.add (.var 18) (.const 134217728)) 28,
    -- 35: let c2 = (x2 + 0x8000000) asr 28 in
    .asr (.add (.var 19) (.const 134217728)) 28,
    -- 36: let c3 = (x3 + 0x8000000) asr 28 in
    .asr (.add (.var 20) (.const 134217728)) 28,
    -- 37: let c4 = (x4 + 0x8000000) asr 28 in
    .asr (.add (.var 21) (.const 134217728)) 28,
    -- 38: let c5 = (x5 + 0x8000000) asr 28 in
    .asr (.add (.var 22) (.const 134217728)) 28,
    -- 39: let c6 = (x6 + 0x8000000) asr 28 in
    .asr (.add (.var 23) (.const 134217728)) 28,
    -- 40: let c7 = (x7 + 0x8000000) asr 28 in
    .asr (.add (.var 24) (.const 134217728)) 28,
    -- 41: let c8 = (x8 + 0x8000000) asr 28 in
    .asr (.add (.var 25) (.const 134217728)) 28,
    -- 42: let c9 = (x9 + 0x8000000) asr 28 in
    .asr (.add (.var 26) (.const 134217728)) 28,
    -- 43: let c10 = (x10 + 0x8000000) asr 28 in
    .asr (.add (.var 27) (.const 134217728)) 28,
    -- 44: let c11 = (x11 + 0x8000000) asr 28 in
    .asr (.add (.var 28) (.const 134217728)) 28,
    -- 45: let c12 = (x12 + 0x8000000) asr 28 in
    .asr (.add (.var 29) (.const 134217728)) 28,
    -- 46: let c13 = (x13 + 0x8000000) asr 28 in
    .asr (.add (.var 30) (.const 134217728)) 28,
    -- 47: let c14 = (x14 + 0x8000000) asr 28 in
    .asr (.add (.var 31) (.const 134217728)) 28,
    -- 48: let c15 = (x15 + 0x8000000) asr 28 in
    .asr (.add (.var 32) (.const 134217728)) 28,
    -- 49: let q0 = x0 - (c0 lsl 28) in
    .sub (.var 17) (.lsl (.var 33) 28),
    -- 50: let q1 = x1 - (c1 lsl 28) in
    .sub (.var 18) (.lsl (.var 34) 28),
    -- 51: let q2 = x2 - (c2 lsl 28) in
    .sub (.var 19) (.lsl (.var 35) 28),
    -- 52: let q3 = x3 - (c3 lsl 28) in
    .sub (.var 20) (.lsl (.var 36) 28),
    -- 53: let q4 = x4 - (c4 lsl 28) in
    .sub (.var 21) (.lsl (.var 37) 28),
    -- 54: let q5 = x5 - (c5 lsl 28) in
    .sub (.var 22) (.lsl (.var 38) 28),
    -- 55: let q6 = x6 - (c6 lsl 28) in
    .sub (.var 23) (.lsl (.var 39) 28),
    -- 56: let q7 = x7 - (c7 lsl 28) in
    .sub (.var 24) (.lsl (.var 40) 28),
    -- 57: let q8 = x8 - (c8 lsl 28) in
    .sub (.var 25) (.lsl (.var 41) 28),
    -- 58: let q9 = x9 - (c9 lsl 28) in
    .sub (.var 26) (.lsl (.var 42) 28),
    -- 59: let q10 = x10 - (c10 lsl 28) in
    .sub (.var 27) (.lsl (.var 43) 28),
    -- 60: let q11 = x11 - (c11 lsl 28) in
    .sub (.var 28) (.lsl (.var 44) 28),
    -- 61: let q12 = x12 - (c12 lsl 28) in
    .sub (.var 29) (.lsl (.var 45) 28),
    -- 62: let q13 = x13 - (c13 lsl 28) in
    .sub (.var 30) (.lsl (.var 46) 28),
    -- 63: let q14 = x14 - (c14 lsl 28) in
    .sub (.var 31) (.lsl (.var 47) 28),
    -- 64: let q15 = x15 - (c15 lsl 28) in
    .sub (.var 32) (.lsl (.var 48) 28),
    -- 65: let y0 = q0 + c15 in
    .add (.var 49) (.var 48),
    -- 66: let y1 = q1 + c0 in
    .add (.var 50) (.var 33),
    -- 67: let y2 = q2 + c1 in
    .add (.var 51) (.var 34),
    -- 68: let y3 = q3 + c2 in
    .add (.var 52) (.var 35),
    -- 69: let y4 = q4 + c3 in
    .add (.var 53) (.var 36),
    -- 70: let y5 = q5 + c4 in
    .add (.var 54) (.var 37),
    -- 71: let y6 = q6 + c5 in
    .add (.var 55) (.var 38),
    -- 72: let y7 = q7 + c6 in
    .add (.var 56) (.var 39),
    -- 73: let y8 = q8 + c7 + c15 in
    .add (.add (.var 57) (.var 40)) (.var 48),
    -- 74: let y9 = q9 + c8 in
    .add (.var 58) (.var 41),
    -- 75: let y10 = q10 + c9 in
    .add (.var 59) (.var 42),
    -- 76: let y11 = q11 + c10 in
    .add (.var 60) (.var 43),
    -- 77: let y12 = q12 + c11 in
    .add (.var 61) (.var 44),
    -- 78: let y13 = q13 + c12 in
    .add (.var 62) (.var 45),
    -- 79: let y14 = q14 + c13 in
    .add (.var 63) (.var 46),
    -- 80: let y15 = q15 + c14 in
    .add (.var 64) (.var 47),
    -- 81: let d0 = (y0 + 0x8000000) asr 28 in
    .asr (.add (.var 65) (.const 134217728)) 28,
    -- 82: let d1 = (y1 + 0x8000000) asr 28 in
    .asr (.add (.var 66) (.const 134217728)) 28,
    -- 83: let d2 = (y2 + 0x8000000) asr 28 in
    .asr (.add (.var 67) (.const 134217728)) 28,
    -- 84: let d3 = (y3 + 0x8000000) asr 28 in
    .asr (.add (.var 68) (.const 134217728)) 28,
    -- 85: let d4 = (y4 + 0x8000000) asr 28 in
    .asr (.add (.var 69) (.const 134217728)) 28,
    -- 86: let d5 = (y5 + 0x8000000) asr 28 in
    .asr (.add (.var 70) (.const 134217728)) 28,
    -- 87: let d6 = (y6 + 0x8000000) asr 28 in
    .asr (.add (.var 71) (.const 134217728)) 28,
    -- 88: let d7 = (y7 + 0x8000000) asr 28 in
    .asr (.add (.var 72) (.const 134217728)) 28,
    -- 89: let d8 = (y8 + 0x8000000) asr 28 in
    .asr (.add (.var 73) (.const 134217728)) 28,
    -- 90: let d9 = (y9 + 0x8000000) asr 28 in
    .asr (.add (.var 74) (.const 134217728)) 28,
    -- 91: let d10 = (y10 + 0x8000000) asr 28 in
    .asr (.add (.var 75) (.const 134217728)) 28,
    -- 92: let d11 = (y11 + 0x8000000) asr 28 in
    .asr (.add (.var 76) (.const 134217728)) 28,
    -- 93: let d12 = (y12 + 0x8000000) asr 28 in
    .asr (.add (.var 77) (.const 134217728)) 28,
    -- 94: let d13 = (y13 + 0x8000000) asr 28 in
    .asr (.add (.var 78) (.const 134217728)) 28,
    -- 95: let d14 = (y14 + 0x8000000) asr 28 in
    .asr (.add (.var 79) (.const 134217728)) 28,
    -- 96: let d15 = (y15 + 0x8000000) asr 28 in
    .asr (.add (.var 80) (.const 134217728)) 28,
    -- 97: let e0 = y0 - (d0 lsl 28) in
    .sub (.var 65) (.lsl (.var 81) 28),
    -- 98: let e1 = y1 - (d1 lsl 28) in
    .sub (.var 66) (.lsl (.var 82) 28),
    -- 99: let e2 = y2 - (d2 lsl 28) in
    .sub (.var 67) (.lsl (.var 83) 28),
    -- 100: let e3 = y3 - (d3 lsl 28) in
    .sub (.var 68) (.lsl (.var 84) 28),
    -- 101: let e4 = y4 - (d4 lsl 28) in
    .sub (.var 69) (.lsl (.var 85) 28),
    -- 102: let e5 = y5 - (d5 lsl 28) in
    .sub (.var 70) (.lsl (.var 86) 28),
    -- 103: let e6 = y6 - (d6 lsl 28) in
    .sub (.var 71) (.lsl (.var 87) 28),
    -- 104: let e7 = y7 - (d7 lsl 28) in
    .sub (.var 72) (.lsl (.var 88) 28),
    -- 105: let e8 = y8 - (d8 lsl 28) in
    .sub (.var 73) (.lsl (.var 89) 28),
    -- 106: let e9 = y9 - (d9 lsl 28) in
    .sub (.var 74) (.lsl (.var 90) 28),
    -- 107: let e10 = y10 - (d10 lsl 28) in
    .sub (.var 75) (.lsl (.var 91) 28),
    -- 108: let e11 = y11 - (d11 lsl 28) in
    .sub (.var 76) (.lsl (.var 92) 28),
    -- 109: let e12 = y12 - (d12 lsl 28) in
    .sub (.var 77) (.lsl (.var 93) 28),
    -- 110: let e13 = y13 - (d13 lsl 28) in
    .sub (.var 78) (.lsl (.var 94) 28),
    -- 111: let e14 = y14 - (d14 lsl 28) in
    .sub (.var 79) (.lsl (.var 95) 28),
    -- 112: let e15 = y15 - (d15 lsl 28) in
    .sub (.var 80) (.lsl (.var 96) 28),
    -- 113: let r0 = e0 + d15 in
    .add (.var 97) (.var 96),
    -- 114: let r1 = e1 + d0 in
    .add (.var 98) (.var 81),
    -- 115: let r2 = e2 + d1 in
    .add (.var 99) (.var 82),
    -- 116: let r3 = e3 + d2 in
    .add (.var 100) (.var 83),
    -- 117: let r4 = e4 + d3 in
    .add (.var 101) (.var 84),
    -- 118: let r5 = e5 + d4 in
    .add (.var 102) (.var 85),
    -- 119: let r6 = e6 + d5 in
    .add (.var 103) (.var 86),
    -- 120: let r7 = e7 + d6 in
    .add (.var 104) (.var 87),
    -- 121: let r8 = e8 + d7 + d15 in
    .add (.add (.var 105) (.var 88)) (.var 96),
    -- 122: let r9 = e9 + d8 in
    .add (.var 106) (.var 89),
    -- 123: let r10 = e10 + d9 in
    .add (.var 107) (.var 90),
    -- 124: let r11 = e11 + d10 in
    .add (.var 108) (.var 91),
    -- 125: let r12 = e12 + d11 in
    .add (.var 109) (.var 92),
    -- 126: let r13 = e13 + d12 in
    .add (.var 110) (.var 93),
    -- 127: let r14 = e14 + d13 in
    .add (.var 111) (.var 94),
    -- 128: let r15 = e15 + d14 in
    .add (.var 112) (.var 95)]
  outputs := [113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128]

/-- `Fe448_kernels.carry` (OCaml int arithmetic). -/
def carryK : Kernel where
  name := "carry"
  wide := false
  inputs := [
    (.limb "a" 0, 268435456),  -- 0 a0
    (.limb "a" 1, 268435456),  -- 1 a1
    (.limb "a" 2, 268435456),  -- 2 a2
    (.limb "a" 3, 268435456),  -- 3 a3
    (.limb "a" 4, 268435456),  -- 4 a4
    (.limb "a" 5, 268435456),  -- 5 a5
    (.limb "a" 6, 268435456),  -- 6 a6
    (.limb "a" 7, 268435456),  -- 7 a7
    (.limb "a" 8, 268435456),  -- 8 a8
    (.limb "a" 9, 268435456),  -- 9 a9
    (.limb "a" 10, 268435456),  -- 10 a10
    (.limb "a" 11, 268435456),  -- 11 a11
    (.limb "a" 12, 268435456),  -- 12 a12
    (.limb "a" 13, 268435456),  -- 13 a13
    (.limb "a" 14, 268435456),  -- 14 a14
    (.limb "a" 15, 268435456)]  -- 15 a15
  names := ["a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "a10", "a11", "a12", "a13", "a14", "a15", "c0", "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10", "c11", "c12", "c13", "c14", "c15", "q0", "q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9", "q10", "q11", "q12", "q13", "q14", "q15", "r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12", "r13", "r14", "r15"]
  stmts := [
    -- 16: let c0 = (a0 + 0x8000000) asr 28 in
    .asr (.add (.var 0) (.const 134217728)) 28,
    -- 17: let c1 = (a1 + 0x8000000) asr 28 in
    .asr (.add (.var 1) (.const 134217728)) 28,
    -- 18: let c2 = (a2 + 0x8000000) asr 28 in
    .asr (.add (.var 2) (.const 134217728)) 28,
    -- 19: let c3 = (a3 + 0x8000000) asr 28 in
    .asr (.add (.var 3) (.const 134217728)) 28,
    -- 20: let c4 = (a4 + 0x8000000) asr 28 in
    .asr (.add (.var 4) (.const 134217728)) 28,
    -- 21: let c5 = (a5 + 0x8000000) asr 28 in
    .asr (.add (.var 5) (.const 134217728)) 28,
    -- 22: let c6 = (a6 + 0x8000000) asr 28 in
    .asr (.add (.var 6) (.const 134217728)) 28,
    -- 23: let c7 = (a7 + 0x8000000) asr 28 in
    .asr (.add (.var 7) (.const 134217728)) 28,
    -- 24: let c8 = (a8 + 0x8000000) asr 28 in
    .asr (.add (.var 8) (.const 134217728)) 28,
    -- 25: let c9 = (a9 + 0x8000000) asr 28 in
    .asr (.add (.var 9) (.const 134217728)) 28,
    -- 26: let c10 = (a10 + 0x8000000) asr 28 in
    .asr (.add (.var 10) (.const 134217728)) 28,
    -- 27: let c11 = (a11 + 0x8000000) asr 28 in
    .asr (.add (.var 11) (.const 134217728)) 28,
    -- 28: let c12 = (a12 + 0x8000000) asr 28 in
    .asr (.add (.var 12) (.const 134217728)) 28,
    -- 29: let c13 = (a13 + 0x8000000) asr 28 in
    .asr (.add (.var 13) (.const 134217728)) 28,
    -- 30: let c14 = (a14 + 0x8000000) asr 28 in
    .asr (.add (.var 14) (.const 134217728)) 28,
    -- 31: let c15 = (a15 + 0x8000000) asr 28 in
    .asr (.add (.var 15) (.const 134217728)) 28,
    -- 32: let q0 = a0 - (c0 lsl 28) in
    .sub (.var 0) (.lsl (.var 16) 28),
    -- 33: let q1 = a1 - (c1 lsl 28) in
    .sub (.var 1) (.lsl (.var 17) 28),
    -- 34: let q2 = a2 - (c2 lsl 28) in
    .sub (.var 2) (.lsl (.var 18) 28),
    -- 35: let q3 = a3 - (c3 lsl 28) in
    .sub (.var 3) (.lsl (.var 19) 28),
    -- 36: let q4 = a4 - (c4 lsl 28) in
    .sub (.var 4) (.lsl (.var 20) 28),
    -- 37: let q5 = a5 - (c5 lsl 28) in
    .sub (.var 5) (.lsl (.var 21) 28),
    -- 38: let q6 = a6 - (c6 lsl 28) in
    .sub (.var 6) (.lsl (.var 22) 28),
    -- 39: let q7 = a7 - (c7 lsl 28) in
    .sub (.var 7) (.lsl (.var 23) 28),
    -- 40: let q8 = a8 - (c8 lsl 28) in
    .sub (.var 8) (.lsl (.var 24) 28),
    -- 41: let q9 = a9 - (c9 lsl 28) in
    .sub (.var 9) (.lsl (.var 25) 28),
    -- 42: let q10 = a10 - (c10 lsl 28) in
    .sub (.var 10) (.lsl (.var 26) 28),
    -- 43: let q11 = a11 - (c11 lsl 28) in
    .sub (.var 11) (.lsl (.var 27) 28),
    -- 44: let q12 = a12 - (c12 lsl 28) in
    .sub (.var 12) (.lsl (.var 28) 28),
    -- 45: let q13 = a13 - (c13 lsl 28) in
    .sub (.var 13) (.lsl (.var 29) 28),
    -- 46: let q14 = a14 - (c14 lsl 28) in
    .sub (.var 14) (.lsl (.var 30) 28),
    -- 47: let q15 = a15 - (c15 lsl 28) in
    .sub (.var 15) (.lsl (.var 31) 28),
    -- 48: let r0 = q0 + c15 in
    .add (.var 32) (.var 31),
    -- 49: let r1 = q1 + c0 in
    .add (.var 33) (.var 16),
    -- 50: let r2 = q2 + c1 in
    .add (.var 34) (.var 17),
    -- 51: let r3 = q3 + c2 in
    .add (.var 35) (.var 18),
    -- 52: let r4 = q4 + c3 in
    .add (.var 36) (.var 19),
    -- 53: let r5 = q5 + c4 in
    .add (.var 37) (.var 20),
    -- 54: let r6 = q6 + c5 in
    .add (.var 38) (.var 21),
    -- 55: let r7 = q7 + c6 in
    .add (.var 39) (.var 22),
    -- 56: let r8 = q8 + c7 + c15 in
    .add (.add (.var 40) (.var 23)) (.var 31),
    -- 57: let r9 = q9 + c8 in
    .add (.var 41) (.var 24),
    -- 58: let r10 = q10 + c9 in
    .add (.var 42) (.var 25),
    -- 59: let r11 = q11 + c10 in
    .add (.var 43) (.var 26),
    -- 60: let r12 = q12 + c11 in
    .add (.var 44) (.var 27),
    -- 61: let r13 = q13 + c12 in
    .add (.var 45) (.var 28),
    -- 62: let r14 = q14 + c13 in
    .add (.var 46) (.var 29),
    -- 63: let r15 = q15 + c14 in
    .add (.var 47) (.var 30)]
  outputs := [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]

/-- The six kernels in source order. -/
def allKernels : List Kernel := [mulK, sqK, addK, subK, mulSmallK, carryK]

end Curve448Formal.Kernels
