(* Generated by tools/gen_fe448_ocaml.py; do not edit by hand.

   Field kernels modulo p = 2^448 - 2^224 - 1 on 16 signed limbs of radix
   2^28. Inputs must be tight (|limb| <= 2^27 + 2^5) unless stated otherwise,
   and outputs are tight; [out] may alias an input. Every kernel is
   straight-line code: it loads its inputs, computes, then stores. The
   generator proves by interval arithmetic that no intermediate exceeds
   the 63-bit integer range. *)

(* Unboxed 64-bit arithmetic for the multiplication kernels. ocamlopt keeps
   let-bound int64 values that are only used by these primitives unboxed,
   so the kernels do not allocate. *)
module Wide = struct
  external ( + ) : int64 -> int64 -> int64 = "%int64_add"
  external ( - ) : int64 -> int64 -> int64 = "%int64_sub"
  external ( * ) : int64 -> int64 -> int64 = "%int64_mul"
  external ( asr ) : int64 -> int -> int64 = "%int64_asr"
  external ( lsl ) : int64 -> int -> int64 = "%int64_lsl"
  external of_int : int -> int64 = "%int64_of_int"
  external to_int : int64 -> int = "%int64_to_int"
end

(* out = a * b mod p *)
let[@inline never] mul (out : int array) (a : int array) (b : int array) : unit =
  let open Wide in
  let a0 = of_int (Array.unsafe_get a 0) in
  let a1 = of_int (Array.unsafe_get a 1) in
  let a2 = of_int (Array.unsafe_get a 2) in
  let a3 = of_int (Array.unsafe_get a 3) in
  let a4 = of_int (Array.unsafe_get a 4) in
  let a5 = of_int (Array.unsafe_get a 5) in
  let a6 = of_int (Array.unsafe_get a 6) in
  let a7 = of_int (Array.unsafe_get a 7) in
  let a8 = of_int (Array.unsafe_get a 8) in
  let a9 = of_int (Array.unsafe_get a 9) in
  let a10 = of_int (Array.unsafe_get a 10) in
  let a11 = of_int (Array.unsafe_get a 11) in
  let a12 = of_int (Array.unsafe_get a 12) in
  let a13 = of_int (Array.unsafe_get a 13) in
  let a14 = of_int (Array.unsafe_get a 14) in
  let a15 = of_int (Array.unsafe_get a 15) in
  let b0 = of_int (Array.unsafe_get b 0) in
  let b1 = of_int (Array.unsafe_get b 1) in
  let b2 = of_int (Array.unsafe_get b 2) in
  let b3 = of_int (Array.unsafe_get b 3) in
  let b4 = of_int (Array.unsafe_get b 4) in
  let b5 = of_int (Array.unsafe_get b 5) in
  let b6 = of_int (Array.unsafe_get b 6) in
  let b7 = of_int (Array.unsafe_get b 7) in
  let b8 = of_int (Array.unsafe_get b 8) in
  let b9 = of_int (Array.unsafe_get b 9) in
  let b10 = of_int (Array.unsafe_get b 10) in
  let b11 = of_int (Array.unsafe_get b 11) in
  let b12 = of_int (Array.unsafe_get b 12) in
  let b13 = of_int (Array.unsafe_get b 13) in
  let b14 = of_int (Array.unsafe_get b 14) in
  let b15 = of_int (Array.unsafe_get b 15) in
  let aa0 = a0 + a8 in
  let aa1 = a1 + a9 in
  let aa2 = a2 + a10 in
  let aa3 = a3 + a11 in
  let aa4 = a4 + a12 in
  let aa5 = a5 + a13 in
  let aa6 = a6 + a14 in
  let aa7 = a7 + a15 in
  let bb0 = b0 + b8 in
  let bb1 = b1 + b9 in
  let bb2 = b2 + b10 in
  let bb3 = b3 + b11 in
  let bb4 = b4 + b12 in
  let bb5 = b5 + b13 in
  let bb6 = b6 + b14 in
  let bb7 = b7 + b15 in
  let l0 = a0 * b0 in
  let l1 = a0 * b1 + a1 * b0 in
  let l2 = a0 * b2 + a1 * b1 + a2 * b0 in
  let l3 = a0 * b3 + a1 * b2 + a2 * b1 + a3 * b0 in
  let l4 = a0 * b4 + a1 * b3 + a2 * b2 + a3 * b1 + a4 * b0 in
  let l5 = a0 * b5 + a1 * b4 + a2 * b3 + a3 * b2 + a4 * b1 + a5 * b0 in
  let l6 = a0 * b6 + a1 * b5 + a2 * b4 + a3 * b3 + a4 * b2 + a5 * b1 + a6 * b0 in
  let l7 = a0 * b7 + a1 * b6 + a2 * b5 + a3 * b4 + a4 * b3 + a5 * b2 + a6 * b1 + a7 * b0 in
  let l8 = a1 * b7 + a2 * b6 + a3 * b5 + a4 * b4 + a5 * b3 + a6 * b2 + a7 * b1 in
  let l9 = a2 * b7 + a3 * b6 + a4 * b5 + a5 * b4 + a6 * b3 + a7 * b2 in
  let l10 = a3 * b7 + a4 * b6 + a5 * b5 + a6 * b4 + a7 * b3 in
  let l11 = a4 * b7 + a5 * b6 + a6 * b5 + a7 * b4 in
  let l12 = a5 * b7 + a6 * b6 + a7 * b5 in
  let l13 = a6 * b7 + a7 * b6 in
  let l14 = a7 * b7 in
  let h0 = a8 * b8 in
  let h1 = a8 * b9 + a9 * b8 in
  let h2 = a8 * b10 + a9 * b9 + a10 * b8 in
  let h3 = a8 * b11 + a9 * b10 + a10 * b9 + a11 * b8 in
  let h4 = a8 * b12 + a9 * b11 + a10 * b10 + a11 * b9 + a12 * b8 in
  let h5 = a8 * b13 + a9 * b12 + a10 * b11 + a11 * b10 + a12 * b9 + a13 * b8 in
  let h6 = a8 * b14 + a9 * b13 + a10 * b12 + a11 * b11 + a12 * b10 + a13 * b9 + a14 * b8 in
  let h7 = a8 * b15 + a9 * b14 + a10 * b13 + a11 * b12 + a12 * b11 + a13 * b10 + a14 * b9 + a15 * b8 in
  let h8 = a9 * b15 + a10 * b14 + a11 * b13 + a12 * b12 + a13 * b11 + a14 * b10 + a15 * b9 in
  let h9 = a10 * b15 + a11 * b14 + a12 * b13 + a13 * b12 + a14 * b11 + a15 * b10 in
  let h10 = a11 * b15 + a12 * b14 + a13 * b13 + a14 * b12 + a15 * b11 in
  let h11 = a12 * b15 + a13 * b14 + a14 * b13 + a15 * b12 in
  let h12 = a13 * b15 + a14 * b14 + a15 * b13 in
  let h13 = a14 * b15 + a15 * b14 in
  let h14 = a15 * b15 in
  let s0 = aa0 * bb0 in
  let s1 = aa0 * bb1 + aa1 * bb0 in
  let s2 = aa0 * bb2 + aa1 * bb1 + aa2 * bb0 in
  let s3 = aa0 * bb3 + aa1 * bb2 + aa2 * bb1 + aa3 * bb0 in
  let s4 = aa0 * bb4 + aa1 * bb3 + aa2 * bb2 + aa3 * bb1 + aa4 * bb0 in
  let s5 = aa0 * bb5 + aa1 * bb4 + aa2 * bb3 + aa3 * bb2 + aa4 * bb1 + aa5 * bb0 in
  let s6 = aa0 * bb6 + aa1 * bb5 + aa2 * bb4 + aa3 * bb3 + aa4 * bb2 + aa5 * bb1 + aa6 * bb0 in
  let s7 = aa0 * bb7 + aa1 * bb6 + aa2 * bb5 + aa3 * bb4 + aa4 * bb3 + aa5 * bb2 + aa6 * bb1 + aa7 * bb0 in
  let s8 = aa1 * bb7 + aa2 * bb6 + aa3 * bb5 + aa4 * bb4 + aa5 * bb3 + aa6 * bb2 + aa7 * bb1 in
  let s9 = aa2 * bb7 + aa3 * bb6 + aa4 * bb5 + aa5 * bb4 + aa6 * bb3 + aa7 * bb2 in
  let s10 = aa3 * bb7 + aa4 * bb6 + aa5 * bb5 + aa6 * bb4 + aa7 * bb3 in
  let s11 = aa4 * bb7 + aa5 * bb6 + aa6 * bb5 + aa7 * bb4 in
  let s12 = aa5 * bb7 + aa6 * bb6 + aa7 * bb5 in
  let s13 = aa6 * bb7 + aa7 * bb6 in
  let s14 = aa7 * bb7 in
  let r0 = l0 + h0 + s8 - l8 in
  let r1 = l1 + h1 + s9 - l9 in
  let r2 = l2 + h2 + s10 - l10 in
  let r3 = l3 + h3 + s11 - l11 in
  let r4 = l4 + h4 + s12 - l12 in
  let r5 = l5 + h5 + s13 - l13 in
  let r6 = l6 + h6 + s14 - l14 in
  let r7 = l7 + h7 in
  let r8 = s0 + h8 + s8 - l0 in
  let r9 = s1 + h9 + s9 - l1 in
  let r10 = s2 + h10 + s10 - l2 in
  let r11 = s3 + h11 + s11 - l3 in
  let r12 = s4 + h12 + s12 - l4 in
  let r13 = s5 + h13 + s13 - l5 in
  let r14 = s6 + h14 + s14 - l6 in
  let r15 = s7 - l7 in
  let c = (r0 + 0x8000000L) asr 28 in
  let r0 = r0 - (c lsl 28) in
  let r1 = r1 + c in
  let c = (r1 + 0x8000000L) asr 28 in
  let r1 = r1 - (c lsl 28) in
  let r2 = r2 + c in
  let c = (r2 + 0x8000000L) asr 28 in
  let r2 = r2 - (c lsl 28) in
  let r3 = r3 + c in
  let c = (r3 + 0x8000000L) asr 28 in
  let r3 = r3 - (c lsl 28) in
  let r4 = r4 + c in
  let c = (r4 + 0x8000000L) asr 28 in
  let r4 = r4 - (c lsl 28) in
  let r5 = r5 + c in
  let c = (r5 + 0x8000000L) asr 28 in
  let r5 = r5 - (c lsl 28) in
  let r6 = r6 + c in
  let c = (r6 + 0x8000000L) asr 28 in
  let r6 = r6 - (c lsl 28) in
  let r7 = r7 + c in
  let c = (r7 + 0x8000000L) asr 28 in
  let r7 = r7 - (c lsl 28) in
  let r8 = r8 + c in
  let c = (r8 + 0x8000000L) asr 28 in
  let r8 = r8 - (c lsl 28) in
  let r9 = r9 + c in
  let c = (r9 + 0x8000000L) asr 28 in
  let r9 = r9 - (c lsl 28) in
  let r10 = r10 + c in
  let c = (r10 + 0x8000000L) asr 28 in
  let r10 = r10 - (c lsl 28) in
  let r11 = r11 + c in
  let c = (r11 + 0x8000000L) asr 28 in
  let r11 = r11 - (c lsl 28) in
  let r12 = r12 + c in
  let c = (r12 + 0x8000000L) asr 28 in
  let r12 = r12 - (c lsl 28) in
  let r13 = r13 + c in
  let c = (r13 + 0x8000000L) asr 28 in
  let r13 = r13 - (c lsl 28) in
  let r14 = r14 + c in
  let c = (r14 + 0x8000000L) asr 28 in
  let r14 = r14 - (c lsl 28) in
  let r15 = r15 + c in
  let c = (r15 + 0x8000000L) asr 28 in
  let r15 = r15 - (c lsl 28) in
  let r0 = r0 + c in
  let r8 = r8 + c in
  let c = (r0 + 0x8000000L) asr 28 in
  let r0 = r0 - (c lsl 28) in
  let r1 = r1 + c in
  let c = (r8 + 0x8000000L) asr 28 in
  let r8 = r8 - (c lsl 28) in
  let r9 = r9 + c in
  Array.unsafe_set out 0 (to_int r0);
  Array.unsafe_set out 1 (to_int r1);
  Array.unsafe_set out 2 (to_int r2);
  Array.unsafe_set out 3 (to_int r3);
  Array.unsafe_set out 4 (to_int r4);
  Array.unsafe_set out 5 (to_int r5);
  Array.unsafe_set out 6 (to_int r6);
  Array.unsafe_set out 7 (to_int r7);
  Array.unsafe_set out 8 (to_int r8);
  Array.unsafe_set out 9 (to_int r9);
  Array.unsafe_set out 10 (to_int r10);
  Array.unsafe_set out 11 (to_int r11);
  Array.unsafe_set out 12 (to_int r12);
  Array.unsafe_set out 13 (to_int r13);
  Array.unsafe_set out 14 (to_int r14);
  Array.unsafe_set out 15 (to_int r15)

(* out = a^2 mod p *)
let[@inline never] sq (out : int array) (a : int array) : unit =
  let open Wide in
  let a0 = of_int (Array.unsafe_get a 0) in
  let a1 = of_int (Array.unsafe_get a 1) in
  let a2 = of_int (Array.unsafe_get a 2) in
  let a3 = of_int (Array.unsafe_get a 3) in
  let a4 = of_int (Array.unsafe_get a 4) in
  let a5 = of_int (Array.unsafe_get a 5) in
  let a6 = of_int (Array.unsafe_get a 6) in
  let a7 = of_int (Array.unsafe_get a 7) in
  let a8 = of_int (Array.unsafe_get a 8) in
  let a9 = of_int (Array.unsafe_get a 9) in
  let a10 = of_int (Array.unsafe_get a 10) in
  let a11 = of_int (Array.unsafe_get a 11) in
  let a12 = of_int (Array.unsafe_get a 12) in
  let a13 = of_int (Array.unsafe_get a 13) in
  let a14 = of_int (Array.unsafe_get a 14) in
  let a15 = of_int (Array.unsafe_get a 15) in
  let aa0 = a0 + a8 in
  let aa1 = a1 + a9 in
  let aa2 = a2 + a10 in
  let aa3 = a3 + a11 in
  let aa4 = a4 + a12 in
  let aa5 = a5 + a13 in
  let aa6 = a6 + a14 in
  let aa7 = a7 + a15 in
  let l0 = a0 * a0 in
  let da0 = a0 + a0 in
  let l1 = da0 * a1 in
  let l2 = da0 * a2 + a1 * a1 in
  let da1 = a1 + a1 in
  let l3 = da0 * a3 + da1 * a2 in
  let l4 = da0 * a4 + da1 * a3 + a2 * a2 in
  let da2 = a2 + a2 in
  let l5 = da0 * a5 + da1 * a4 + da2 * a3 in
  let l6 = da0 * a6 + da1 * a5 + da2 * a4 + a3 * a3 in
  let da3 = a3 + a3 in
  let l7 = da0 * a7 + da1 * a6 + da2 * a5 + da3 * a4 in
  let l8 = da1 * a7 + da2 * a6 + da3 * a5 + a4 * a4 in
  let da4 = a4 + a4 in
  let l9 = da2 * a7 + da3 * a6 + da4 * a5 in
  let l10 = da3 * a7 + da4 * a6 + a5 * a5 in
  let da5 = a5 + a5 in
  let l11 = da4 * a7 + da5 * a6 in
  let l12 = da5 * a7 + a6 * a6 in
  let da6 = a6 + a6 in
  let l13 = da6 * a7 in
  let l14 = a7 * a7 in
  let h0 = a8 * a8 in
  let da8 = a8 + a8 in
  let h1 = da8 * a9 in
  let h2 = da8 * a10 + a9 * a9 in
  let da9 = a9 + a9 in
  let h3 = da8 * a11 + da9 * a10 in
  let h4 = da8 * a12 + da9 * a11 + a10 * a10 in
  let da10 = a10 + a10 in
  let h5 = da8 * a13 + da9 * a12 + da10 * a11 in
  let h6 = da8 * a14 + da9 * a13 + da10 * a12 + a11 * a11 in
  let da11 = a11 + a11 in
  let h7 = da8 * a15 + da9 * a14 + da10 * a13 + da11 * a12 in
  let h8 = da9 * a15 + da10 * a14 + da11 * a13 + a12 * a12 in
  let da12 = a12 + a12 in
  let h9 = da10 * a15 + da11 * a14 + da12 * a13 in
  let h10 = da11 * a15 + da12 * a14 + a13 * a13 in
  let da13 = a13 + a13 in
  let h11 = da12 * a15 + da13 * a14 in
  let h12 = da13 * a15 + a14 * a14 in
  let da14 = a14 + a14 in
  let h13 = da14 * a15 in
  let h14 = a15 * a15 in
  let s0 = aa0 * aa0 in
  let daa0 = aa0 + aa0 in
  let s1 = daa0 * aa1 in
  let s2 = daa0 * aa2 + aa1 * aa1 in
  let daa1 = aa1 + aa1 in
  let s3 = daa0 * aa3 + daa1 * aa2 in
  let s4 = daa0 * aa4 + daa1 * aa3 + aa2 * aa2 in
  let daa2 = aa2 + aa2 in
  let s5 = daa0 * aa5 + daa1 * aa4 + daa2 * aa3 in
  let s6 = daa0 * aa6 + daa1 * aa5 + daa2 * aa4 + aa3 * aa3 in
  let daa3 = aa3 + aa3 in
  let s7 = daa0 * aa7 + daa1 * aa6 + daa2 * aa5 + daa3 * aa4 in
  let s8 = daa1 * aa7 + daa2 * aa6 + daa3 * aa5 + aa4 * aa4 in
  let daa4 = aa4 + aa4 in
  let s9 = daa2 * aa7 + daa3 * aa6 + daa4 * aa5 in
  let s10 = daa3 * aa7 + daa4 * aa6 + aa5 * aa5 in
  let daa5 = aa5 + aa5 in
  let s11 = daa4 * aa7 + daa5 * aa6 in
  let s12 = daa5 * aa7 + aa6 * aa6 in
  let daa6 = aa6 + aa6 in
  let s13 = daa6 * aa7 in
  let s14 = aa7 * aa7 in
  let r0 = l0 + h0 + s8 - l8 in
  let r1 = l1 + h1 + s9 - l9 in
  let r2 = l2 + h2 + s10 - l10 in
  let r3 = l3 + h3 + s11 - l11 in
  let r4 = l4 + h4 + s12 - l12 in
  let r5 = l5 + h5 + s13 - l13 in
  let r6 = l6 + h6 + s14 - l14 in
  let r7 = l7 + h7 in
  let r8 = s0 + h8 + s8 - l0 in
  let r9 = s1 + h9 + s9 - l1 in
  let r10 = s2 + h10 + s10 - l2 in
  let r11 = s3 + h11 + s11 - l3 in
  let r12 = s4 + h12 + s12 - l4 in
  let r13 = s5 + h13 + s13 - l5 in
  let r14 = s6 + h14 + s14 - l6 in
  let r15 = s7 - l7 in
  let c = (r0 + 0x8000000L) asr 28 in
  let r0 = r0 - (c lsl 28) in
  let r1 = r1 + c in
  let c = (r1 + 0x8000000L) asr 28 in
  let r1 = r1 - (c lsl 28) in
  let r2 = r2 + c in
  let c = (r2 + 0x8000000L) asr 28 in
  let r2 = r2 - (c lsl 28) in
  let r3 = r3 + c in
  let c = (r3 + 0x8000000L) asr 28 in
  let r3 = r3 - (c lsl 28) in
  let r4 = r4 + c in
  let c = (r4 + 0x8000000L) asr 28 in
  let r4 = r4 - (c lsl 28) in
  let r5 = r5 + c in
  let c = (r5 + 0x8000000L) asr 28 in
  let r5 = r5 - (c lsl 28) in
  let r6 = r6 + c in
  let c = (r6 + 0x8000000L) asr 28 in
  let r6 = r6 - (c lsl 28) in
  let r7 = r7 + c in
  let c = (r7 + 0x8000000L) asr 28 in
  let r7 = r7 - (c lsl 28) in
  let r8 = r8 + c in
  let c = (r8 + 0x8000000L) asr 28 in
  let r8 = r8 - (c lsl 28) in
  let r9 = r9 + c in
  let c = (r9 + 0x8000000L) asr 28 in
  let r9 = r9 - (c lsl 28) in
  let r10 = r10 + c in
  let c = (r10 + 0x8000000L) asr 28 in
  let r10 = r10 - (c lsl 28) in
  let r11 = r11 + c in
  let c = (r11 + 0x8000000L) asr 28 in
  let r11 = r11 - (c lsl 28) in
  let r12 = r12 + c in
  let c = (r12 + 0x8000000L) asr 28 in
  let r12 = r12 - (c lsl 28) in
  let r13 = r13 + c in
  let c = (r13 + 0x8000000L) asr 28 in
  let r13 = r13 - (c lsl 28) in
  let r14 = r14 + c in
  let c = (r14 + 0x8000000L) asr 28 in
  let r14 = r14 - (c lsl 28) in
  let r15 = r15 + c in
  let c = (r15 + 0x8000000L) asr 28 in
  let r15 = r15 - (c lsl 28) in
  let r0 = r0 + c in
  let r8 = r8 + c in
  let c = (r0 + 0x8000000L) asr 28 in
  let r0 = r0 - (c lsl 28) in
  let r1 = r1 + c in
  let c = (r8 + 0x8000000L) asr 28 in
  let r8 = r8 - (c lsl 28) in
  let r9 = r9 + c in
  Array.unsafe_set out 0 (to_int r0);
  Array.unsafe_set out 1 (to_int r1);
  Array.unsafe_set out 2 (to_int r2);
  Array.unsafe_set out 3 (to_int r3);
  Array.unsafe_set out 4 (to_int r4);
  Array.unsafe_set out 5 (to_int r5);
  Array.unsafe_set out 6 (to_int r6);
  Array.unsafe_set out 7 (to_int r7);
  Array.unsafe_set out 8 (to_int r8);
  Array.unsafe_set out 9 (to_int r9);
  Array.unsafe_set out 10 (to_int r10);
  Array.unsafe_set out 11 (to_int r11);
  Array.unsafe_set out 12 (to_int r12);
  Array.unsafe_set out 13 (to_int r13);
  Array.unsafe_set out 14 (to_int r14);
  Array.unsafe_set out 15 (to_int r15)

(* out = a + b mod p *)
let[@inline never] add (out : int array) (a : int array) (b : int array) : unit =
  let a0 = Array.unsafe_get a 0 in
  let a1 = Array.unsafe_get a 1 in
  let a2 = Array.unsafe_get a 2 in
  let a3 = Array.unsafe_get a 3 in
  let a4 = Array.unsafe_get a 4 in
  let a5 = Array.unsafe_get a 5 in
  let a6 = Array.unsafe_get a 6 in
  let a7 = Array.unsafe_get a 7 in
  let a8 = Array.unsafe_get a 8 in
  let a9 = Array.unsafe_get a 9 in
  let a10 = Array.unsafe_get a 10 in
  let a11 = Array.unsafe_get a 11 in
  let a12 = Array.unsafe_get a 12 in
  let a13 = Array.unsafe_get a 13 in
  let a14 = Array.unsafe_get a 14 in
  let a15 = Array.unsafe_get a 15 in
  let b0 = Array.unsafe_get b 0 in
  let b1 = Array.unsafe_get b 1 in
  let b2 = Array.unsafe_get b 2 in
  let b3 = Array.unsafe_get b 3 in
  let b4 = Array.unsafe_get b 4 in
  let b5 = Array.unsafe_get b 5 in
  let b6 = Array.unsafe_get b 6 in
  let b7 = Array.unsafe_get b 7 in
  let b8 = Array.unsafe_get b 8 in
  let b9 = Array.unsafe_get b 9 in
  let b10 = Array.unsafe_get b 10 in
  let b11 = Array.unsafe_get b 11 in
  let b12 = Array.unsafe_get b 12 in
  let b13 = Array.unsafe_get b 13 in
  let b14 = Array.unsafe_get b 14 in
  let b15 = Array.unsafe_get b 15 in
  let x0 = a0 + b0 in
  let x1 = a1 + b1 in
  let x2 = a2 + b2 in
  let x3 = a3 + b3 in
  let x4 = a4 + b4 in
  let x5 = a5 + b5 in
  let x6 = a6 + b6 in
  let x7 = a7 + b7 in
  let x8 = a8 + b8 in
  let x9 = a9 + b9 in
  let x10 = a10 + b10 in
  let x11 = a11 + b11 in
  let x12 = a12 + b12 in
  let x13 = a13 + b13 in
  let x14 = a14 + b14 in
  let x15 = a15 + b15 in
  let c0 = (x0 + 0x8000000) asr 28 in
  let c1 = (x1 + 0x8000000) asr 28 in
  let c2 = (x2 + 0x8000000) asr 28 in
  let c3 = (x3 + 0x8000000) asr 28 in
  let c4 = (x4 + 0x8000000) asr 28 in
  let c5 = (x5 + 0x8000000) asr 28 in
  let c6 = (x6 + 0x8000000) asr 28 in
  let c7 = (x7 + 0x8000000) asr 28 in
  let c8 = (x8 + 0x8000000) asr 28 in
  let c9 = (x9 + 0x8000000) asr 28 in
  let c10 = (x10 + 0x8000000) asr 28 in
  let c11 = (x11 + 0x8000000) asr 28 in
  let c12 = (x12 + 0x8000000) asr 28 in
  let c13 = (x13 + 0x8000000) asr 28 in
  let c14 = (x14 + 0x8000000) asr 28 in
  let c15 = (x15 + 0x8000000) asr 28 in
  let q0 = x0 - (c0 lsl 28) in
  let q1 = x1 - (c1 lsl 28) in
  let q2 = x2 - (c2 lsl 28) in
  let q3 = x3 - (c3 lsl 28) in
  let q4 = x4 - (c4 lsl 28) in
  let q5 = x5 - (c5 lsl 28) in
  let q6 = x6 - (c6 lsl 28) in
  let q7 = x7 - (c7 lsl 28) in
  let q8 = x8 - (c8 lsl 28) in
  let q9 = x9 - (c9 lsl 28) in
  let q10 = x10 - (c10 lsl 28) in
  let q11 = x11 - (c11 lsl 28) in
  let q12 = x12 - (c12 lsl 28) in
  let q13 = x13 - (c13 lsl 28) in
  let q14 = x14 - (c14 lsl 28) in
  let q15 = x15 - (c15 lsl 28) in
  let r0 = q0 + c15 in
  let r1 = q1 + c0 in
  let r2 = q2 + c1 in
  let r3 = q3 + c2 in
  let r4 = q4 + c3 in
  let r5 = q5 + c4 in
  let r6 = q6 + c5 in
  let r7 = q7 + c6 in
  let r8 = q8 + c7 + c15 in
  let r9 = q9 + c8 in
  let r10 = q10 + c9 in
  let r11 = q11 + c10 in
  let r12 = q12 + c11 in
  let r13 = q13 + c12 in
  let r14 = q14 + c13 in
  let r15 = q15 + c14 in
  Array.unsafe_set out 0 r0;
  Array.unsafe_set out 1 r1;
  Array.unsafe_set out 2 r2;
  Array.unsafe_set out 3 r3;
  Array.unsafe_set out 4 r4;
  Array.unsafe_set out 5 r5;
  Array.unsafe_set out 6 r6;
  Array.unsafe_set out 7 r7;
  Array.unsafe_set out 8 r8;
  Array.unsafe_set out 9 r9;
  Array.unsafe_set out 10 r10;
  Array.unsafe_set out 11 r11;
  Array.unsafe_set out 12 r12;
  Array.unsafe_set out 13 r13;
  Array.unsafe_set out 14 r14;
  Array.unsafe_set out 15 r15

(* out = a - b mod p *)
let[@inline never] sub (out : int array) (a : int array) (b : int array) : unit =
  let a0 = Array.unsafe_get a 0 in
  let a1 = Array.unsafe_get a 1 in
  let a2 = Array.unsafe_get a 2 in
  let a3 = Array.unsafe_get a 3 in
  let a4 = Array.unsafe_get a 4 in
  let a5 = Array.unsafe_get a 5 in
  let a6 = Array.unsafe_get a 6 in
  let a7 = Array.unsafe_get a 7 in
  let a8 = Array.unsafe_get a 8 in
  let a9 = Array.unsafe_get a 9 in
  let a10 = Array.unsafe_get a 10 in
  let a11 = Array.unsafe_get a 11 in
  let a12 = Array.unsafe_get a 12 in
  let a13 = Array.unsafe_get a 13 in
  let a14 = Array.unsafe_get a 14 in
  let a15 = Array.unsafe_get a 15 in
  let b0 = Array.unsafe_get b 0 in
  let b1 = Array.unsafe_get b 1 in
  let b2 = Array.unsafe_get b 2 in
  let b3 = Array.unsafe_get b 3 in
  let b4 = Array.unsafe_get b 4 in
  let b5 = Array.unsafe_get b 5 in
  let b6 = Array.unsafe_get b 6 in
  let b7 = Array.unsafe_get b 7 in
  let b8 = Array.unsafe_get b 8 in
  let b9 = Array.unsafe_get b 9 in
  let b10 = Array.unsafe_get b 10 in
  let b11 = Array.unsafe_get b 11 in
  let b12 = Array.unsafe_get b 12 in
  let b13 = Array.unsafe_get b 13 in
  let b14 = Array.unsafe_get b 14 in
  let b15 = Array.unsafe_get b 15 in
  let x0 = a0 - b0 in
  let x1 = a1 - b1 in
  let x2 = a2 - b2 in
  let x3 = a3 - b3 in
  let x4 = a4 - b4 in
  let x5 = a5 - b5 in
  let x6 = a6 - b6 in
  let x7 = a7 - b7 in
  let x8 = a8 - b8 in
  let x9 = a9 - b9 in
  let x10 = a10 - b10 in
  let x11 = a11 - b11 in
  let x12 = a12 - b12 in
  let x13 = a13 - b13 in
  let x14 = a14 - b14 in
  let x15 = a15 - b15 in
  let c0 = (x0 + 0x8000000) asr 28 in
  let c1 = (x1 + 0x8000000) asr 28 in
  let c2 = (x2 + 0x8000000) asr 28 in
  let c3 = (x3 + 0x8000000) asr 28 in
  let c4 = (x4 + 0x8000000) asr 28 in
  let c5 = (x5 + 0x8000000) asr 28 in
  let c6 = (x6 + 0x8000000) asr 28 in
  let c7 = (x7 + 0x8000000) asr 28 in
  let c8 = (x8 + 0x8000000) asr 28 in
  let c9 = (x9 + 0x8000000) asr 28 in
  let c10 = (x10 + 0x8000000) asr 28 in
  let c11 = (x11 + 0x8000000) asr 28 in
  let c12 = (x12 + 0x8000000) asr 28 in
  let c13 = (x13 + 0x8000000) asr 28 in
  let c14 = (x14 + 0x8000000) asr 28 in
  let c15 = (x15 + 0x8000000) asr 28 in
  let q0 = x0 - (c0 lsl 28) in
  let q1 = x1 - (c1 lsl 28) in
  let q2 = x2 - (c2 lsl 28) in
  let q3 = x3 - (c3 lsl 28) in
  let q4 = x4 - (c4 lsl 28) in
  let q5 = x5 - (c5 lsl 28) in
  let q6 = x6 - (c6 lsl 28) in
  let q7 = x7 - (c7 lsl 28) in
  let q8 = x8 - (c8 lsl 28) in
  let q9 = x9 - (c9 lsl 28) in
  let q10 = x10 - (c10 lsl 28) in
  let q11 = x11 - (c11 lsl 28) in
  let q12 = x12 - (c12 lsl 28) in
  let q13 = x13 - (c13 lsl 28) in
  let q14 = x14 - (c14 lsl 28) in
  let q15 = x15 - (c15 lsl 28) in
  let r0 = q0 + c15 in
  let r1 = q1 + c0 in
  let r2 = q2 + c1 in
  let r3 = q3 + c2 in
  let r4 = q4 + c3 in
  let r5 = q5 + c4 in
  let r6 = q6 + c5 in
  let r7 = q7 + c6 in
  let r8 = q8 + c7 + c15 in
  let r9 = q9 + c8 in
  let r10 = q10 + c9 in
  let r11 = q11 + c10 in
  let r12 = q12 + c11 in
  let r13 = q13 + c12 in
  let r14 = q14 + c13 in
  let r15 = q15 + c14 in
  Array.unsafe_set out 0 r0;
  Array.unsafe_set out 1 r1;
  Array.unsafe_set out 2 r2;
  Array.unsafe_set out 3 r3;
  Array.unsafe_set out 4 r4;
  Array.unsafe_set out 5 r5;
  Array.unsafe_set out 6 r6;
  Array.unsafe_set out 7 r7;
  Array.unsafe_set out 8 r8;
  Array.unsafe_set out 9 r9;
  Array.unsafe_set out 10 r10;
  Array.unsafe_set out 11 r11;
  Array.unsafe_set out 12 r12;
  Array.unsafe_set out 13 r13;
  Array.unsafe_set out 14 r14;
  Array.unsafe_set out 15 r15

(* out = a * k mod p for |k| <= 2^16 *)
let[@inline never] mul_small (out : int array) (a : int array) (k : int) : unit =
  let a0 = Array.unsafe_get a 0 in
  let a1 = Array.unsafe_get a 1 in
  let a2 = Array.unsafe_get a 2 in
  let a3 = Array.unsafe_get a 3 in
  let a4 = Array.unsafe_get a 4 in
  let a5 = Array.unsafe_get a 5 in
  let a6 = Array.unsafe_get a 6 in
  let a7 = Array.unsafe_get a 7 in
  let a8 = Array.unsafe_get a 8 in
  let a9 = Array.unsafe_get a 9 in
  let a10 = Array.unsafe_get a 10 in
  let a11 = Array.unsafe_get a 11 in
  let a12 = Array.unsafe_get a 12 in
  let a13 = Array.unsafe_get a 13 in
  let a14 = Array.unsafe_get a 14 in
  let a15 = Array.unsafe_get a 15 in
  let x0 = a0 * k in
  let x1 = a1 * k in
  let x2 = a2 * k in
  let x3 = a3 * k in
  let x4 = a4 * k in
  let x5 = a5 * k in
  let x6 = a6 * k in
  let x7 = a7 * k in
  let x8 = a8 * k in
  let x9 = a9 * k in
  let x10 = a10 * k in
  let x11 = a11 * k in
  let x12 = a12 * k in
  let x13 = a13 * k in
  let x14 = a14 * k in
  let x15 = a15 * k in
  let c0 = (x0 + 0x8000000) asr 28 in
  let c1 = (x1 + 0x8000000) asr 28 in
  let c2 = (x2 + 0x8000000) asr 28 in
  let c3 = (x3 + 0x8000000) asr 28 in
  let c4 = (x4 + 0x8000000) asr 28 in
  let c5 = (x5 + 0x8000000) asr 28 in
  let c6 = (x6 + 0x8000000) asr 28 in
  let c7 = (x7 + 0x8000000) asr 28 in
  let c8 = (x8 + 0x8000000) asr 28 in
  let c9 = (x9 + 0x8000000) asr 28 in
  let c10 = (x10 + 0x8000000) asr 28 in
  let c11 = (x11 + 0x8000000) asr 28 in
  let c12 = (x12 + 0x8000000) asr 28 in
  let c13 = (x13 + 0x8000000) asr 28 in
  let c14 = (x14 + 0x8000000) asr 28 in
  let c15 = (x15 + 0x8000000) asr 28 in
  let q0 = x0 - (c0 lsl 28) in
  let q1 = x1 - (c1 lsl 28) in
  let q2 = x2 - (c2 lsl 28) in
  let q3 = x3 - (c3 lsl 28) in
  let q4 = x4 - (c4 lsl 28) in
  let q5 = x5 - (c5 lsl 28) in
  let q6 = x6 - (c6 lsl 28) in
  let q7 = x7 - (c7 lsl 28) in
  let q8 = x8 - (c8 lsl 28) in
  let q9 = x9 - (c9 lsl 28) in
  let q10 = x10 - (c10 lsl 28) in
  let q11 = x11 - (c11 lsl 28) in
  let q12 = x12 - (c12 lsl 28) in
  let q13 = x13 - (c13 lsl 28) in
  let q14 = x14 - (c14 lsl 28) in
  let q15 = x15 - (c15 lsl 28) in
  let y0 = q0 + c15 in
  let y1 = q1 + c0 in
  let y2 = q2 + c1 in
  let y3 = q3 + c2 in
  let y4 = q4 + c3 in
  let y5 = q5 + c4 in
  let y6 = q6 + c5 in
  let y7 = q7 + c6 in
  let y8 = q8 + c7 + c15 in
  let y9 = q9 + c8 in
  let y10 = q10 + c9 in
  let y11 = q11 + c10 in
  let y12 = q12 + c11 in
  let y13 = q13 + c12 in
  let y14 = q14 + c13 in
  let y15 = q15 + c14 in
  let d0 = (y0 + 0x8000000) asr 28 in
  let d1 = (y1 + 0x8000000) asr 28 in
  let d2 = (y2 + 0x8000000) asr 28 in
  let d3 = (y3 + 0x8000000) asr 28 in
  let d4 = (y4 + 0x8000000) asr 28 in
  let d5 = (y5 + 0x8000000) asr 28 in
  let d6 = (y6 + 0x8000000) asr 28 in
  let d7 = (y7 + 0x8000000) asr 28 in
  let d8 = (y8 + 0x8000000) asr 28 in
  let d9 = (y9 + 0x8000000) asr 28 in
  let d10 = (y10 + 0x8000000) asr 28 in
  let d11 = (y11 + 0x8000000) asr 28 in
  let d12 = (y12 + 0x8000000) asr 28 in
  let d13 = (y13 + 0x8000000) asr 28 in
  let d14 = (y14 + 0x8000000) asr 28 in
  let d15 = (y15 + 0x8000000) asr 28 in
  let e0 = y0 - (d0 lsl 28) in
  let e1 = y1 - (d1 lsl 28) in
  let e2 = y2 - (d2 lsl 28) in
  let e3 = y3 - (d3 lsl 28) in
  let e4 = y4 - (d4 lsl 28) in
  let e5 = y5 - (d5 lsl 28) in
  let e6 = y6 - (d6 lsl 28) in
  let e7 = y7 - (d7 lsl 28) in
  let e8 = y8 - (d8 lsl 28) in
  let e9 = y9 - (d9 lsl 28) in
  let e10 = y10 - (d10 lsl 28) in
  let e11 = y11 - (d11 lsl 28) in
  let e12 = y12 - (d12 lsl 28) in
  let e13 = y13 - (d13 lsl 28) in
  let e14 = y14 - (d14 lsl 28) in
  let e15 = y15 - (d15 lsl 28) in
  let r0 = e0 + d15 in
  let r1 = e1 + d0 in
  let r2 = e2 + d1 in
  let r3 = e3 + d2 in
  let r4 = e4 + d3 in
  let r5 = e5 + d4 in
  let r6 = e6 + d5 in
  let r7 = e7 + d6 in
  let r8 = e8 + d7 + d15 in
  let r9 = e9 + d8 in
  let r10 = e10 + d9 in
  let r11 = e11 + d10 in
  let r12 = e12 + d11 in
  let r13 = e13 + d12 in
  let r14 = e14 + d13 in
  let r15 = e15 + d14 in
  Array.unsafe_set out 0 r0;
  Array.unsafe_set out 1 r1;
  Array.unsafe_set out 2 r2;
  Array.unsafe_set out 3 r3;
  Array.unsafe_set out 4 r4;
  Array.unsafe_set out 5 r5;
  Array.unsafe_set out 6 r6;
  Array.unsafe_set out 7 r7;
  Array.unsafe_set out 8 r8;
  Array.unsafe_set out 9 r9;
  Array.unsafe_set out 10 r10;
  Array.unsafe_set out 11 r11;
  Array.unsafe_set out 12 r12;
  Array.unsafe_set out 13 r13;
  Array.unsafe_set out 14 r14;
  Array.unsafe_set out 15 r15

(* out = a mod p with tight limbs, for |a_i| <= 2^28 *)
let[@inline never] carry (out : int array) (a : int array) : unit =
  let a0 = Array.unsafe_get a 0 in
  let a1 = Array.unsafe_get a 1 in
  let a2 = Array.unsafe_get a 2 in
  let a3 = Array.unsafe_get a 3 in
  let a4 = Array.unsafe_get a 4 in
  let a5 = Array.unsafe_get a 5 in
  let a6 = Array.unsafe_get a 6 in
  let a7 = Array.unsafe_get a 7 in
  let a8 = Array.unsafe_get a 8 in
  let a9 = Array.unsafe_get a 9 in
  let a10 = Array.unsafe_get a 10 in
  let a11 = Array.unsafe_get a 11 in
  let a12 = Array.unsafe_get a 12 in
  let a13 = Array.unsafe_get a 13 in
  let a14 = Array.unsafe_get a 14 in
  let a15 = Array.unsafe_get a 15 in
  let c0 = (a0 + 0x8000000) asr 28 in
  let c1 = (a1 + 0x8000000) asr 28 in
  let c2 = (a2 + 0x8000000) asr 28 in
  let c3 = (a3 + 0x8000000) asr 28 in
  let c4 = (a4 + 0x8000000) asr 28 in
  let c5 = (a5 + 0x8000000) asr 28 in
  let c6 = (a6 + 0x8000000) asr 28 in
  let c7 = (a7 + 0x8000000) asr 28 in
  let c8 = (a8 + 0x8000000) asr 28 in
  let c9 = (a9 + 0x8000000) asr 28 in
  let c10 = (a10 + 0x8000000) asr 28 in
  let c11 = (a11 + 0x8000000) asr 28 in
  let c12 = (a12 + 0x8000000) asr 28 in
  let c13 = (a13 + 0x8000000) asr 28 in
  let c14 = (a14 + 0x8000000) asr 28 in
  let c15 = (a15 + 0x8000000) asr 28 in
  let q0 = a0 - (c0 lsl 28) in
  let q1 = a1 - (c1 lsl 28) in
  let q2 = a2 - (c2 lsl 28) in
  let q3 = a3 - (c3 lsl 28) in
  let q4 = a4 - (c4 lsl 28) in
  let q5 = a5 - (c5 lsl 28) in
  let q6 = a6 - (c6 lsl 28) in
  let q7 = a7 - (c7 lsl 28) in
  let q8 = a8 - (c8 lsl 28) in
  let q9 = a9 - (c9 lsl 28) in
  let q10 = a10 - (c10 lsl 28) in
  let q11 = a11 - (c11 lsl 28) in
  let q12 = a12 - (c12 lsl 28) in
  let q13 = a13 - (c13 lsl 28) in
  let q14 = a14 - (c14 lsl 28) in
  let q15 = a15 - (c15 lsl 28) in
  let r0 = q0 + c15 in
  let r1 = q1 + c0 in
  let r2 = q2 + c1 in
  let r3 = q3 + c2 in
  let r4 = q4 + c3 in
  let r5 = q5 + c4 in
  let r6 = q6 + c5 in
  let r7 = q7 + c6 in
  let r8 = q8 + c7 + c15 in
  let r9 = q9 + c8 in
  let r10 = q10 + c9 in
  let r11 = q11 + c10 in
  let r12 = q12 + c11 in
  let r13 = q13 + c12 in
  let r14 = q14 + c13 in
  let r15 = q15 + c14 in
  Array.unsafe_set out 0 r0;
  Array.unsafe_set out 1 r1;
  Array.unsafe_set out 2 r2;
  Array.unsafe_set out 3 r3;
  Array.unsafe_set out 4 r4;
  Array.unsafe_set out 5 r5;
  Array.unsafe_set out 6 r6;
  Array.unsafe_set out 7 r7;
  Array.unsafe_set out 8 r8;
  Array.unsafe_set out 9 r9;
  Array.unsafe_set out 10 r10;
  Array.unsafe_set out 11 r11;
  Array.unsafe_set out 12 r12;
  Array.unsafe_set out 13 r13;
  Array.unsafe_set out 14 r14;
  Array.unsafe_set out 15 r15

(* Largest intermediate magnitudes proven by the generator: mul 2^60.32, sq 2^60.32, add 2^29.58, sub 2^29.58, mul_small 2^44.00, carry 2^29.58. *)
