(* Generated by tools/gen_keccak_ocaml.py; do not edit by hand.

   Keccak-f[1600] (FIPS 202, section 3). The state is 25 lanes stored
   little-endian in a 200-byte buffer, lane A[x, y] at byte offset
   8 (x + 5 y). Each round loads the lanes into unboxed int64 locals
   (aXY is A[X, Y]), computes theta (cX, dX), rho and pi (bXY is
   A'[X, Y] before chi), chi and iota, and stores the lanes back. *)

module Lane = struct
  external ( lxor ) : int64 -> int64 -> int64 = "%int64_xor"
  external ( land ) : int64 -> int64 -> int64 = "%int64_and"
  external ( lor ) : int64 -> int64 -> int64 = "%int64_or"
  external ( lsl ) : int64 -> int -> int64 = "%int64_lsl"
  external ( lsr ) : int64 -> int -> int64 = "%int64_lsr"
  external get : bytes -> int -> int64 = "%caml_bytes_get64u"
  external set : bytes -> int -> int64 -> unit = "%caml_bytes_set64u"
  external swap : int64 -> int64 = "%bswap_int64"

  let[@inline] load s i = if Sys.big_endian then swap (get s i) else get s i

  let[@inline] store s i v =
    if Sys.big_endian then set s i (swap v) else set s i v
end

(* RC[i_r], from the rc LFSR of FIPS 202, Algorithm 5. *)
let round_constants =
  [|
    0x0000000000000001L;
    0x0000000000008082L;
    0x800000000000808aL;
    0x8000000080008000L;
    0x000000000000808bL;
    0x0000000080000001L;
    0x8000000080008081L;
    0x8000000000008009L;
    0x000000000000008aL;
    0x0000000000000088L;
    0x0000000080008009L;
    0x000000008000000aL;
    0x000000008000808bL;
    0x800000000000008bL;
    0x8000000000008089L;
    0x8000000000008003L;
    0x8000000000008002L;
    0x8000000000000080L;
    0x000000000000800aL;
    0x800000008000000aL;
    0x8000000080008081L;
    0x8000000000008080L;
    0x0000000080000001L;
    0x8000000080008008L;
  |]

let permute (s : bytes) =
  let open Lane in
  for round = 0 to 23 do
    let a00 = load s 0 in
    let a10 = load s 8 in
    let a20 = load s 16 in
    let a30 = load s 24 in
    let a40 = load s 32 in
    let a01 = load s 40 in
    let a11 = load s 48 in
    let a21 = load s 56 in
    let a31 = load s 64 in
    let a41 = load s 72 in
    let a02 = load s 80 in
    let a12 = load s 88 in
    let a22 = load s 96 in
    let a32 = load s 104 in
    let a42 = load s 112 in
    let a03 = load s 120 in
    let a13 = load s 128 in
    let a23 = load s 136 in
    let a33 = load s 144 in
    let a43 = load s 152 in
    let a04 = load s 160 in
    let a14 = load s 168 in
    let a24 = load s 176 in
    let a34 = load s 184 in
    let a44 = load s 192 in
    (* theta *)
    let c0 = a00 lxor a01 lxor a02 lxor a03 lxor a04 in
    let c1 = a10 lxor a11 lxor a12 lxor a13 lxor a14 in
    let c2 = a20 lxor a21 lxor a22 lxor a23 lxor a24 in
    let c3 = a30 lxor a31 lxor a32 lxor a33 lxor a34 in
    let c4 = a40 lxor a41 lxor a42 lxor a43 lxor a44 in
    let d0 = c4 lxor ((c1 lsl 1) lor (c1 lsr 63)) in
    let d1 = c0 lxor ((c2 lsl 1) lor (c2 lsr 63)) in
    let d2 = c1 lxor ((c3 lsl 1) lor (c3 lsr 63)) in
    let d3 = c2 lxor ((c4 lsl 1) lor (c4 lsr 63)) in
    let d4 = c3 lxor ((c0 lsl 1) lor (c0 lsr 63)) in
    (* rho and pi *)
    let b00 = a00 lxor d0 in
    let t10 = a10 lxor d1 in
    let b02 = (t10 lsl 1) lor (t10 lsr 63) in
    let t20 = a20 lxor d2 in
    let b04 = (t20 lsl 62) lor (t20 lsr 2) in
    let t30 = a30 lxor d3 in
    let b01 = (t30 lsl 28) lor (t30 lsr 36) in
    let t40 = a40 lxor d4 in
    let b03 = (t40 lsl 27) lor (t40 lsr 37) in
    let t01 = a01 lxor d0 in
    let b13 = (t01 lsl 36) lor (t01 lsr 28) in
    let t11 = a11 lxor d1 in
    let b10 = (t11 lsl 44) lor (t11 lsr 20) in
    let t21 = a21 lxor d2 in
    let b12 = (t21 lsl 6) lor (t21 lsr 58) in
    let t31 = a31 lxor d3 in
    let b14 = (t31 lsl 55) lor (t31 lsr 9) in
    let t41 = a41 lxor d4 in
    let b11 = (t41 lsl 20) lor (t41 lsr 44) in
    let t02 = a02 lxor d0 in
    let b21 = (t02 lsl 3) lor (t02 lsr 61) in
    let t12 = a12 lxor d1 in
    let b23 = (t12 lsl 10) lor (t12 lsr 54) in
    let t22 = a22 lxor d2 in
    let b20 = (t22 lsl 43) lor (t22 lsr 21) in
    let t32 = a32 lxor d3 in
    let b22 = (t32 lsl 25) lor (t32 lsr 39) in
    let t42 = a42 lxor d4 in
    let b24 = (t42 lsl 39) lor (t42 lsr 25) in
    let t03 = a03 lxor d0 in
    let b34 = (t03 lsl 41) lor (t03 lsr 23) in
    let t13 = a13 lxor d1 in
    let b31 = (t13 lsl 45) lor (t13 lsr 19) in
    let t23 = a23 lxor d2 in
    let b33 = (t23 lsl 15) lor (t23 lsr 49) in
    let t33 = a33 lxor d3 in
    let b30 = (t33 lsl 21) lor (t33 lsr 43) in
    let t43 = a43 lxor d4 in
    let b32 = (t43 lsl 8) lor (t43 lsr 56) in
    let t04 = a04 lxor d0 in
    let b42 = (t04 lsl 18) lor (t04 lsr 46) in
    let t14 = a14 lxor d1 in
    let b44 = (t14 lsl 2) lor (t14 lsr 62) in
    let t24 = a24 lxor d2 in
    let b41 = (t24 lsl 61) lor (t24 lsr 3) in
    let t34 = a34 lxor d3 in
    let b43 = (t34 lsl 56) lor (t34 lsr 8) in
    let t44 = a44 lxor d4 in
    let b40 = (t44 lsl 14) lor (t44 lsr 50) in
    (* chi and iota *)
    store s 0 (b00 lxor ((b10 lxor -1L) land b20) lxor Array.unsafe_get round_constants round);
    store s 8 (b10 lxor ((b20 lxor -1L) land b30));
    store s 16 (b20 lxor ((b30 lxor -1L) land b40));
    store s 24 (b30 lxor ((b40 lxor -1L) land b00));
    store s 32 (b40 lxor ((b00 lxor -1L) land b10));
    store s 40 (b01 lxor ((b11 lxor -1L) land b21));
    store s 48 (b11 lxor ((b21 lxor -1L) land b31));
    store s 56 (b21 lxor ((b31 lxor -1L) land b41));
    store s 64 (b31 lxor ((b41 lxor -1L) land b01));
    store s 72 (b41 lxor ((b01 lxor -1L) land b11));
    store s 80 (b02 lxor ((b12 lxor -1L) land b22));
    store s 88 (b12 lxor ((b22 lxor -1L) land b32));
    store s 96 (b22 lxor ((b32 lxor -1L) land b42));
    store s 104 (b32 lxor ((b42 lxor -1L) land b02));
    store s 112 (b42 lxor ((b02 lxor -1L) land b12));
    store s 120 (b03 lxor ((b13 lxor -1L) land b23));
    store s 128 (b13 lxor ((b23 lxor -1L) land b33));
    store s 136 (b23 lxor ((b33 lxor -1L) land b43));
    store s 144 (b33 lxor ((b43 lxor -1L) land b03));
    store s 152 (b43 lxor ((b03 lxor -1L) land b13));
    store s 160 (b04 lxor ((b14 lxor -1L) land b24));
    store s 168 (b14 lxor ((b24 lxor -1L) land b34));
    store s 176 (b24 lxor ((b34 lxor -1L) land b44));
    store s 184 (b34 lxor ((b44 lxor -1L) land b04));
    store s 192 (b44 lxor ((b04 lxor -1L) land b14))
  done
