#!/usr/bin/env python3
"""Generate lib/ocaml/keccak.ml, Keccak-f[1600] for the pure OCaml backend.

The permutation is written out from FIPS 202, section 3: the rho offsets come
from Algorithm 2, the pi lane positions from Algorithm 3, and the round
constants from the rc LFSR of Algorithm 5; none is copied from a table. Each
round of the generated code loads the 25 lanes into unboxed int64 locals,
computes theta, rho, pi, chi and iota as straight-line code and stores the
lanes back, with no branch or table lookup that depends on the state.

Before emitting, the script runs the same permutation in Python inside a
SHAKE256 sponge and compares it with hashlib on messages around the rate.

Usage:
  python3 tools/gen_keccak_ocaml.py > lib/ocaml/keccak.ml
  python3 tools/gen_keccak_ocaml.py --check lib/ocaml/keccak.ml
"""

import hashlib
import sys

ROUNDS = 24
MASK = (1 << 64) - 1


def rho_offsets():
    """FIPS 202, Algorithm 2: offsets[(x, y)] in bits."""
    offsets = {(0, 0): 0}
    x, y = 1, 0
    for t in range(24):
        offsets[(x, y)] = ((t + 1) * (t + 2) // 2) % 64
        x, y = y, (2 * x + 3 * y) % 5
    return offsets


def rc(t):
    """FIPS 202, Algorithm 5: the output bit of the LFSR after t steps."""
    if t % 255 == 0:
        return 1
    r = [1, 0, 0, 0, 0, 0, 0, 0]
    for _ in range(t % 255):
        r = [0] + r
        r[0] ^= r[8]
        r[4] ^= r[8]
        r[5] ^= r[8]
        r[6] ^= r[8]
        r = r[:8]
    return r[0]


def round_constant(ir):
    """FIPS 202, Algorithm 6, step 2: RC for round ir."""
    value = 0
    for j in range(7):
        value |= rc(j + 7 * ir) << ((1 << j) - 1)
    return value


def pi_target(x, y):
    """FIPS 202, Algorithm 3 sets A'[x, y] = A[(x + 3 y) mod 5, x]; so lane
    A[x, y] moves to A'[y, (2 x + 3 y) mod 5]."""
    return y, (2 * x + 3 * y) % 5


def rotl(v, n):
    return ((v << n) | (v >> (64 - n))) & MASK if n else v


def permute(lanes):
    """Reference Keccak-f[1600] over a dict {(x, y): int}."""
    offsets = rho_offsets()
    a = dict(lanes)
    for ir in range(ROUNDS):
        c = [a[(x, 0)] ^ a[(x, 1)] ^ a[(x, 2)] ^ a[(x, 3)] ^ a[(x, 4)] for x in range(5)]
        d = [c[(x - 1) % 5] ^ rotl(c[(x + 1) % 5], 1) for x in range(5)]
        b = {}
        for x in range(5):
            for y in range(5):
                b[pi_target(x, y)] = rotl(a[(x, y)] ^ d[x], offsets[(x, y)])
        for x in range(5):
            for y in range(5):
                a[(x, y)] = b[(x, y)] ^ ((b[((x + 1) % 5, y)] ^ MASK) & b[((x + 2) % 5, y)])
        a[(0, 0)] ^= round_constant(ir)
    return a


def shake256(message, length):
    rate = 136
    state = bytearray(200)
    padded = bytearray(message) + b"\x1f"
    padded += bytes(-len(padded) % rate)
    padded[-1] ^= 0x80

    def run():
        lanes = dict(((x, y), int.from_bytes(state[8 * (x + 5 * y):8 * (x + 5 * y) + 8], "little"))
                     for x in range(5) for y in range(5))
        lanes = permute(lanes)
        for (x, y), v in lanes.items():
            state[8 * (x + 5 * y):8 * (x + 5 * y) + 8] = v.to_bytes(8, "little")

    for block in range(0, len(padded), rate):
        for i in range(rate):
            state[i] ^= padded[block + i]
        run()
    out = bytearray()
    while len(out) < length:
        out += state[:rate]
        if len(out) < length:
            run()
    return bytes(out[:length])


def self_test():
    for n in (0, 1, 135, 136, 137, 271, 272, 500):
        message = bytes((i * 7 + n) & 0xff for i in range(n))
        if shake256(message, 300) != hashlib.shake_256(message).digest(300):
            raise SystemExit("the reference permutation does not match hashlib (length %d)" % n)


def lane(x, y):
    return "a%d%d" % (x, y)


def generate():
    offsets = rho_offsets()
    lines = [
        "(* Generated by tools/gen_keccak_ocaml.py; do not edit by hand.",
        "",
        "   Keccak-f[1600] (FIPS 202, section 3). The state is 25 lanes stored",
        "   little-endian in a 200-byte buffer, lane A[x, y] at byte offset",
        "   8 (x + 5 y). Each round loads the lanes into unboxed int64 locals",
        "   (aXY is A[X, Y]), computes theta (cX, dX), rho and pi (bXY is",
        "   A'[X, Y] before chi), chi and iota, and stores the lanes back. *)",
        "",
        "module Lane = struct",
        '  external ( lxor ) : int64 -> int64 -> int64 = "%int64_xor"',
        '  external ( land ) : int64 -> int64 -> int64 = "%int64_and"',
        '  external ( lor ) : int64 -> int64 -> int64 = "%int64_or"',
        '  external ( lsl ) : int64 -> int -> int64 = "%int64_lsl"',
        '  external ( lsr ) : int64 -> int -> int64 = "%int64_lsr"',
        '  external get : bytes -> int -> int64 = "%caml_bytes_get64u"',
        '  external set : bytes -> int -> int64 -> unit = "%caml_bytes_set64u"',
        '  external swap : int64 -> int64 = "%bswap_int64"',
        "",
        "  let[@inline] load s i = if Sys.big_endian then swap (get s i) else get s i",
        "",
        "  let[@inline] store s i v =",
        "    if Sys.big_endian then set s i (swap v) else set s i v",
        "end",
        "",
        "(* RC[i_r], from the rc LFSR of FIPS 202, Algorithm 5. *)",
        "let round_constants =",
        "  [|",
    ]
    for ir in range(ROUNDS):
        lines.append("    0x%016xL;" % round_constant(ir))
    lines += [
        "  |]",
        "",
        "let permute (s : bytes) =",
        "  let open Lane in",
        "  for round = 0 to %d do" % (ROUNDS - 1),
    ]
    for y in range(5):
        for x in range(5):
            lines.append("    let %s = load s %d in" % (lane(x, y), 8 * (x + 5 * y)))
    lines.append("    (* theta *)")
    for x in range(5):
        lines.append("    let c%d = %s in" % (x, " lxor ".join(lane(x, y) for y in range(5))))
    for x in range(5):
        prev, nxt = (x - 1) % 5, (x + 1) % 5
        lines.append("    let d%d = c%d lxor ((c%d lsl 1) lor (c%d lsr 63)) in" % (x, prev, nxt, nxt))
    lines.append("    (* rho and pi *)")
    for y in range(5):
        for x in range(5):
            tx, ty = pi_target(x, y)
            r = offsets[(x, y)]
            source = "%s lxor d%d" % (lane(x, y), x)
            if r == 0:
                lines.append("    let b%d%d = %s in" % (tx, ty, source))
            else:
                lines.append("    let t%d%d = %s in" % (x, y, source))
                lines.append("    let b%d%d = (t%d%d lsl %d) lor (t%d%d lsr %d) in"
                             % (tx, ty, x, y, r, x, y, 64 - r))
    lines.append("    (* chi and iota *)")
    stores = []
    for y in range(5):
        for x in range(5):
            x1, x2 = (x + 1) % 5, (x + 2) % 5
            expr = "b%d%d lxor ((b%d%d lxor -1L) land b%d%d)" % (x, y, x1, y, x2, y)
            if (x, y) == (0, 0):
                expr = "%s lxor Array.unsafe_get round_constants round" % expr
            stores.append("    store s %d (%s)" % (8 * (x + 5 * y), expr))
    lines.append(";\n".join(stores))
    lines.append("  done")
    return "\n".join(lines) + "\n"


def main(argv):
    self_test()
    text = generate()
    if len(argv) == 3 and argv[1] == "--check":
        with open(argv[2], encoding="ascii") as handle:
            if handle.read() != text:
                sys.stderr.write("%s is out of date; regenerate it\n" % argv[2])
                return 1
        return 0
    if len(argv) != 1:
        sys.stderr.write(__doc__)
        return 2
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
