#!/usr/bin/env python3
"""Generate the edwards448 constants and fixed-base tables.

  lib/c/native/curve448_tables.h  (C backend: fiat-crypto 56-bit limbs)
  lib/ocaml/table448.ml           (OCaml backend: signed 28-bit limbs)

Both hold d, the RFC 8032 base point, and (t + 1) * 2^(32 j) * B for
j = 0..13, t = 0..7 in affine form with d * x * y. Everything is computed here
with Python integers, independently of the field arithmetic that consumes it;
the test suite cross-checks every entry against a Zarith model as well.

Usage:
  python3 tools/gen_tables.py > lib/c/native/curve448_tables.h
  python3 tools/gen_tables.py --ocaml > lib/ocaml/table448.ml
  python3 tools/gen_tables.py [--ocaml] --check FILE
"""

import sys

P = 2**448 - 2**224 - 1
D = (-39081) % P
# RFC 8032, section 5.2: the edwards448 base point.
BX = int(
    "22458004029592430018760433409989603624678964163256413424612546168695"
    "0415467406032909029192869357953282578032075146446173674602635247710"
)
BY = int(
    "29881921007848149267601793044393067343754404015408024209592824137233"
    "1506189835876003536878655418784733982303233503462500531545062832660"
)

TABLES = 14  # one table per 32 bits of scalar (8 signed radix-16 digits)
ENTRIES = 8  # multiples 1..8
SPACING_BITS = 32


def on_curve(x, y):
    return (x * x + y * y - 1 - D * x * x * y * y) % P == 0


def add(p1, p2):
    """Affine edwards448 addition (a = 1); complete because d is a non-square."""
    (x1, y1), (x2, y2) = p1, p2
    t = D * x1 * x2 * y1 * y2 % P
    x3 = (x1 * y2 + y1 * x2) * pow(1 + t, P - 2, P) % P
    y3 = (y1 * y2 - x1 * x2) * pow(1 - t, P - 2, P) % P
    return x3, y3


def limbs(n):
    assert 0 <= n < P
    return [(n >> (56 * i)) & (2**56 - 1) for i in range(8)]


def fe_literal(n):
    return "{{" + ", ".join("UINT64_C(0x%014x)" % l for l in limbs(n)) + "}}"


def table_points():
    """Yield (j, t, x, y) for every table entry."""
    base = (BX, BY)
    for j in range(TABLES):
        point = base
        for t in range(ENTRIES):
            assert on_curve(*point)
            yield j, t, point[0], point[1]
            point = add(point, base)
        for _ in range(SPACING_BITS):
            base = add(base, base)


HALF28 = 1 << 27
TIGHT28 = (1 << 27) + (1 << 5)


def balanced_limbs(n):
    """16 signed radix-2^28 limbs of n, carried exactly as the OCaml backend's
    carry does, so that every limb is tight."""
    assert 0 <= n < P
    u = [(n >> (28 * i)) & ((1 << 28) - 1) for i in range(16)]
    c = 0
    for i in range(16):
        x = u[i] + c
        c = (x + HALF28) >> 28
        u[i] = x - (c << 28)
    u[0] += c
    u[8] += c
    for i in (0, 8):
        c = (u[i] + HALF28) >> 28
        u[i] -= c << 28
        u[i + 1] += c
    assert sum(l << (28 * i) for i, l in enumerate(u)) % P == n
    assert all(abs(l) <= TIGHT28 for l in u)
    return u


def ocaml_literal(values):
    return "; ".join(str(v) if v >= 0 else "(%d)" % v for v in values)


def generate_ocaml():
    assert on_curve(BX, BY)
    assert pow(D, (P - 1) // 2, P) == P - 1, "d must be a non-square"
    out = []
    emit = out.append
    emit("(* Generated by tools/gen_tables.py --ocaml; do not edit by hand.")
    emit("")
    emit("   Field elements are 16 signed limbs of radix 2^28 in balanced form,")
    emit("   |limb| <= 2^27, so they satisfy the kernels' tight bound. *)")
    emit("")
    emit("(* d = -39081 mod p *)")
    emit("let d = [| %s |]" % ocaml_literal(balanced_limbs(D)))
    emit("")
    emit("(* RFC 8032 edwards448 base point B *)")
    emit("let base_x = [| %s |]" % ocaml_literal(balanced_limbs(BX)))
    emit("let base_y = [| %s |]" % ocaml_literal(balanced_limbs(BY)))
    emit("")
    emit("(* Limb i of coordinate c (0: x, 1: y, 2: d x y) of (t + 1) 2^(%d j) B is" % SPACING_BITS)
    emit("   base.((((j * 8) + t) * 48) + (c * 16) + i). *)")
    emit("let base =")
    emit("  [|")
    for j, t, x, y in table_points():
        dt = D * x * y % P
        limbs_all = balanced_limbs(x) + balanced_limbs(y) + balanced_limbs(dt)
        emit("    (* %d * 2^%d B *)" % (t + 1, SPACING_BITS * j))
        for c in range(3):
            emit("    %s;" % ocaml_literal(limbs_all[16 * c:16 * (c + 1)]))
    emit("  |]")
    return "\n".join(out) + "\n"


def generate():
    assert on_curve(BX, BY)
    assert pow(D, (P - 1) // 2, P) == P - 1, "d must be a non-square"
    out = []
    emit = out.append
    emit("/* Generated by tools/gen_tables.py; do not edit by hand. */")
    emit("")
    emit("/* Field elements are fiat-crypto tight p448 limbs: eight 56-bit")
    emit("   little-endian digits of the canonical representative. */")
    emit("")
    emit("/* d = -39081 mod p */")
    emit("static const fe FE_EDWARDS_D = %s;" % fe_literal(D))
    emit("")
    emit("/* RFC 8032 edwards448 base point B, affine x and y. */")
    emit("static const fe FE_BASE_X = %s;" % fe_literal(BX))
    emit("static const fe FE_BASE_Y = %s;" % fe_literal(BY))
    emit("")
    emit("/* ED448_BASE_TABLE[j][t] = (t + 1) * 2^(%d * j) * B as affine" % SPACING_BITS)
    emit("   (x, y, d * x * y). */")
    emit("static const ge448_precomp ED448_BASE_TABLE[%d][%d] = {" % (TABLES, ENTRIES))
    base = (BX, BY)
    for j in range(TABLES):
        emit("  { /* 2^%d * B */" % (SPACING_BITS * j))
        point = base
        for t in range(ENTRIES):
            x, y = point
            assert on_curve(x, y)
            dt = D * x * y % P
            emit("    {%s," % fe_literal(x))
            emit("     %s," % fe_literal(y))
            emit("     %s}%s" % (fe_literal(dt), "," if t + 1 < ENTRIES else ""))
            point = add(point, base)
        emit("  }%s" % ("," if j + 1 < TABLES else ""))
        for _ in range(SPACING_BITS):
            base = add(base, base)
    emit("};")
    return "\n".join(out) + "\n"


def main(argv):
    args = argv[1:]
    ocaml = "--ocaml" in args
    args = [a for a in args if a != "--ocaml"]
    text = generate_ocaml() if ocaml else generate()
    if len(args) == 2 and args[0] == "--check":
        with open(args[1], encoding="ascii") as handle:
            if handle.read() != text:
                sys.stderr.write("%s is out of date; regenerate it\n" % args[1])
                return 1
        return 0
    if args:
        sys.stderr.write(__doc__)
        return 2
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
